### ISSUE TITLE
Reverse Lookup Deviation URLs or Content URLs for Deviations

### ISSUE THREAD

**Issue by kupiakos** [DeviantArt/DeviantArt-API#100]
It would be useful to be able to i.e. retrieve a `deviationid` based on either the link to the deviation, or the link to the image. For example, I should be able to use either of these:

 - [`http://cryptid-creations.deviantart.com/art/Daily-Paint-1268-Duck-a-L-orange-608488495`][1] or
 - [`http://orig08.deviantart.net/9895/f/2016/132/d/b/daily_paint__1268__duck_a_l_orange_by_cryptid_creations-da2a0q7.png`][2]

and be able to retrieve the `deviationid` `5265D692-E6F0-5B5A-AD34-394BD546B241`.

I don't currently see an endpoint that would help with that. It's possible there is a way to reverse engineer it, but I'd rather use documented methods.

  [1]: http://cryptid-creations.deviantart.com/art/Daily-Paint-1268-Duck-a-L-orange-608488495
  [2]: http://orig08.deviantart.net/9895/f/2016/132/d/b/daily_paint__1268__duck_a_l_orange_by_cryptid_creations-da2a0q7.png

**Comment by muteor** [comment]
The API is designed specifically to not allow this, the idea is that images/deviations are discovered via api resources not by any other means.

**Comment by kupiakos** [comment]
Why? If one is creating an dA app, how is it expected to be able to open up dA links if the API does not support any of this? If someone shares a DeviantArt on some social medium, they're going to be posting links. These links should be able to be opened in an app, regardless of whether they "discovered" the deviations through the app.

URLs and IDs seem very fragmented, making the API nearly useless for real-life usage. At that point, it's easier to load the webpage directly and parse the HTML to try to scrape information, completely negating the API's existence.

With the [oEmbed API](https://www.deviantart.com/developers/oembed) one can retrieve the link to point to, but no more. No comments or more valuable information can be accessed this way. It also doesn't appear to work with direct links.

At least with the Tumblr API, the post ID is stored in each link, which can be extracted and the API can be queried using an original Tumblr URL. Is there a way to do so with DeviantArt or fav.me links? I see numbers, but no indication of how to use them, especially considering there's simply not enough information to store a UUID in the URL.

The specific reason I ask of this is to be able to improve a Reddit bot so that when someone posts a direct DeviantArt link, a comment can be posted linking back to the original page, providing source attribution. Currently, the easiest way to do so is by doing a reverse image search, which seems completely ridiculous.

**Comment by muteor** [comment]
So fav.me and image urls use base36 int encoded ids. If you have the url you can get the app url from the `apple-itunes-app` meta header. I think that should work for link attribution, we just wont be adding an endpoint to do that.

**Comment by kupiakos** [comment]
OK, that's definitely useful for finding source attribution, seeing the ID at the end of a picture is identical to the fav.me link. With this example, I'm seeing the base-36 decode of `a2a0q7` is `608488495`, which is what appears at the end of the deviation page and in the "Embed" code of a page. I'm getting a 403 Forbidden when trying to use the fav.me link directly (http://fav.me/da2a0q7). I'm not sure why, as I'm not incredibly familiar with using fav.me. While I can still use the oEmbed API on the fav.me link to find the author's name and URL, the oEmbed information doesn't appear to provide the deviantart.com URL I (think I) need to GET and request the UUID. One small hole in my plan for direct link to `deviationid`, unless I'm doing something incredibly stupid with fav.me I'm not aware of. Any advice with that?

If I do have the deviation page link, It looks like `document.querySelector("head > meta[name='apple-itunes-app'")['content']` gives me `"app-id=925219396, app-argument=DeviantArt://deviation/5265D692-E6F0-5B5A-AD34-394BD546B241"`. There's the UUID I need! Not sure what `app-id` represents, or if it provides any valuable information.

The meta headers appear to be very useful. Does a full GET request have to be done on a URL to retrieve the data contained in the `apple-itunes-app` meta header? Are the meta headers guaranteed to be stable, at least in some fashion?

**Comment by kupiakos** [comment]
An update on this: it appears that my 403 Forbidden errors with `fav.me` are fixed if I use HTTPS. However, this results in a certificate error (as the certificate is for deviantart.com). My current workaround is to perform all `fav.me` queries with HTTPS, ignoring invalid certificates.

**Comment by the-vindicar** [comment]
@kupiakos Did you manage to circumvent this issue? I'm doing pretty much the same thing you did, and ran into the same problem of API being useless.
P.S.: If you wish to avoid offtopic, you can contact me via email on my profile.

**Comment by SomewhatDamaged** [comment]
Well, anyone coming at this later, this is how I do things:

As mentioned above, using fav.me/ (it will happily take either the base-36 number or the base-10 version) to get the location of the actual deviation. Then I do a HTTPS GET of that page and extract the DeviationID from it.
After this, I then use the following endpoints:
`https://www.deviantart.com/api/v1/oauth2/deviation/{deviation_id}`
`https://www.deviantart.com/api/v1/oauth2/deviation/metadata`
to fetch all the required data (metadata endpoint gives you the full description, which for some reason is stripped from the deviation data).

The only issue is my unfurler (image sourcing bot for Discord) is now hitting deviantart.com too often and they have tossed me in the 403 hole. They have assured me that there is no way to resolve this and will not tell me what is the safe rate limit for their site. Also, their robots.txt file lists no limits or speed restrictions for deviations. Yes, DeviantArt are being poopy heads about this.

Alternatives? There are two!

First, you need to build a flow to login a regular user account to deviantart.com. The trick, I found out by accident, is that an authenticated user bypasses that 403 hole. So you make your bot log in as a user and then send the correct cookies (with each request) and bam, you have bypassed the 403 hole. If you hit a 403, just toss the cookies and log in again.

Second, and I will only be implementing this if they block the first bypass, is to use the `https://www.deviantart.com/api/v1/oauth2/gallery/all` endpoint and loop through/fetch results until I find the right entry. This will be messy. Really messy. I will of course cache matches, but initially at least this is going to result in a lot of API hits/loops when people try to source older deviations.

DeviantArt devs, if you are reading this for some odd reason, why not make a single endpoint that allows a base-36/base-10 ID number and just returns the DeviationID? This will save your web servers/API from being hammered more than they are already.

**Comment by SomewhatDamaged** [comment]
Well, DeviantArt have removed the deviationID from deviation pages again. So, have moved to using `https://www.deviantart.com/api/v1/oauth2/gallery/all` and heavily caching the results.

DeviantArt devs: congratulations, you have made getting data about one image now _more_ difficult than FurAffinity—and they don't have an API.

**Comment by muteor** [comment]
@SomewhatDamaged I have added the meta tag back for the UUID, you can find it in the `da:appurl` property.

**Comment by Veetaha** [comment]
> The API is designed specifically to not allow this, the idea is that images/deviations are discovered via api resources not by any other means.

@muteor could you explain why the API was designed to not allow this, and can't it be extended to allow this?

Your suggestion about parsing the HTML meta tag is a workaround for the problem, but not a robust solution. The problems with this workaround:

- Querying the HTML page requires passing cookies, which have an undocumented format, otherwise if no cookies are passed you get 403 Forbidden.
- The HTML format is also undocumented. The `da:appurl` meta tag is not guaranteed to be present.
- The HTML contains hundreds of kilobytes of redundant data. Downloading all of that introduces huge latencies (around 1 second), which are on the hot path of user interaction for me
- This makes fetching the deviation from the API span two requests (query HTML, query the API) instead of one anyway, so the latency is even worse

It seems to me the brokenness of this is obvious.

@muteor, to be very explicit, could you give us an expanded answer to my question at the top of this comment and the pain points that I described? That would be very nice

**Comment by SomewhatDamaged** [comment]
> @SomewhatDamaged I have added the meta tag back for the UUID, you can find it in the `da:appurl` property.

While that is appreciated, I will point out I still have to juggle cookies and login sessions to be able to access any pages since your web servers have decided to blackhole my IP. This, without any warning in your `robots.txt` file at all about any rate limits.

I believe I will continue using the pure API method I described above. So far that hasn't failed on me and it _is_ how you said deviationIDs are intended to be found.
