### ISSUE TITLE
Check for valid DeviantArt user with Client Credentials Grant

### ISSUE THREAD

**Issue by whoacowboy** [DeviantArt/DeviantArt-API#105]
I am looking for a way to determine if a deviantArt username is active/being used via the API and Client Credentials. 

It is pretty straight forward with Authorization Code Grant or Implicit Grant using whois.

I am open to any solution really. We are running a promotion were a dA user can refer another dA user t our site and we'll give them some points. I wanted to check to see if the user existed on dA before letting them submit the username.

**Comment by joshtwo** [comment]
Try using HTTP HEAD to request http://<username you're testing>.deviantart.com and see if it 404s or not.

**Comment by muteor** [comment]
Will take a look into this, we can probably make that client cred endpoint.

**Comment by whoacowboy** [comment]
@muteor thanks! it would be cool if we could get as much public info about the user from that endpoint. You figure you have to have client credentials and if you abuse it, they could be revoked. 

@joshtwo I am doing it this way now, would just like something that is more "official"

**Comment by muteor** [comment]
No plans to do this in near future...
