### ISSUE TITLE
Client credentials question Using Node and Express

### ISSUE THREAD

**Issue by donhenton** [DeviantArt/DeviantArt-API#106]
I'm running a node application to act as a proxy for the public apis via the client_credentials system.  I get a 403 using request-promise for the following: With absolutely nothing else:

https://www.deviantart.com/oauth2/token?grant_type=client_credentials&client_id=0&client_secret=fred

Yet this succeeds as does putting the url into my browser, and postman.

curl --request GET \
  --url 'https://www.deviantart.com/oauth2/token?grant_type=client_credentials&client_id=0&client_secret=fred' \
   
The server is currently localhost.

Maybe this is my ignorance when it comes to CORS or something like that, but I'm calling from a node express app, so I don't see that applying.

Any help greatly appreciated. I hate to use github for newbie questions, but a FAQ would be a great help!

**Comment by muteor** [comment]
To make requests to the API you must set a user agent header and have request compression on. Looking at docs I think you want something like:

```
var options = {
    uri: 'https://...',
    headers: {
        'User-Agent': 'Request-Promise'
    },
    json: true, // Automatically parses the JSON string in the response
    gzip: true
};
```
