### ISSUE TITLE
Login options: SSO

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#109]
Hi,
is there a way (is it allowed) to use Single SignOn with DA? As currently each time I request need a token, user have to manually enter credentials, even though he already did it a moment ago.

Another question is if it possible to implement in future OAuth that allows manual credentials provision without usage of a web-wrapper?

**Comment by muteor** [comment]
It is possible to do SSO using our api, though a lot of it depends on the context in which you do that. Really SSO should only be implemented by server-side clients where you have good control over client_id/client_secret.

Why do your users need to re-enter credentials? Could you explain a little more?

Regards manual credentials, if you mean being able to send username+password to obtain tokens we will never be implementing that. The reason being is we don't want to encourage users to enter their username+password into anything other than deviantat.com, allowing third-parties access to a users credentials is bad practice.

**Comment by Viachaslau-Zinkevich** [comment]
What I want to achieve is get several access tokens for different processes: One for foreground app running, and one for background tasks. 

Another reason is that when token gets corrupted during refreshing (if for some reason network disconnected and I can’t get refreshed token, the app requires user to authorize once again to get new token.
For authorization I use Microsoft WebAuthenticationBroker to get code from Da api. It should be able to do sso, but for some reasons it doesn’t with DA and each time Authorization page is called

**Comment by muteor** [comment]
Sounds like the webview isn't storing cookies, if the user is logged in and the app is authorized it should redirect without the user doing anything.

**Comment by Viachaslau-Zinkevich** [comment]
Right, but the thing is that this specific regime is expected to save cookies, and as far as I know, it does for let's say Favcebook or Twitter. Could there be some reason why DA's are not saved? Anything specific there?

**Comment by muteor** [comment]
No we have a pretty normal cookie setup, just need the auth cookies and you should be good.

**Comment by Viachaslau-Zinkevich** [comment]
That is strange, but thanks. I guess Microsoft has screwed something, as every time I call service, it open Web View with the process(
