### ISSUE TITLE
Add option to quietly upload to category.

### ISSUE THREAD

**Issue by mancoast** [DeviantArt/DeviantArt-API#110]
Hello,

I use your fantastic API service for lossless preservation of 7680×4320+ fractal animation sequences.
Please help mask these massive uploads by adding an option for me add the artwork to the fractal category, but not display in the http://www.deviantart.com/browse/all/digitalart/fractals/.

**I sincerely apologize for this disruption.**

Please consider that each and every image uploaded is _unique and original art_.
This art needs to be set free.
I require a quiet upload feature because the art must be indexed via category, but there exists no need to display pictures in the gallery view.

Thanks,
coast

**Comment by mancoast** [comment]
The exact API call is the stash/publish call:
Please add option to hide the upload from Gallery.

'https://www.deviantart.com/api/v1/oauth2/stash/publish'

            send = [('access_token', self.oauth.access_token),
                    ('is_mature', 'false'),
                    ('agree_submission', 'true'), 
                    ('agree_tos', 'true'),
                    ('catpath', category_path),
                    ('feature', 'true'),
                    ('allow_comments', 'true'),
                    ('display_resolution', '0'),
                    ('sharing', 'allow'),
                    ('license_options[creative_commons]', 'true'),
                    ('license_options[commercial]', 'true'),
                    ('license_options[modify]', 'share'),
                    ('allow_free_download', 'true'),
                    ('add_watermark', 'false'),
                    ('itemid', str(itemid)),]

**Comment by muteor** [comment]
Only way to do that is to publish to scraps, which you can do by not specifying a category.

**Comment by mancoast** [comment]
works like a charm
thanks!
