### ISSUE TITLE
Client Credentials Token Expires Immediately? 

### ISSUE THREAD

**Issue by MahxieNoodle** [DeviantArt/DeviantArt-API#111]
Hello, I think I may be missing something. I thought that the token you receive using "Client Credentials" lasted one hour. When I try to reuse the token within the hour I get a 403 error. If I request a new token every time it works. Is it supposed to work like that?

**Comment by muteor** [comment]
It should work, whats the body of the 403 error?

**Comment by MahxieNoodle** [comment]
I can't seem to reproduce it again. I think my database may have been messing something up. After changing it I no longer get a 403. Thanks. Sorry!
