### ISSUE TITLE
Endpoint not found: GET /deviation/{deviationid}

### ISSUE THREAD

**Issue by Zeimyth** [DeviantArt/DeviantArt-API#113]
I cannot reach the "get deviation" endpoint from the DeviantArt Developers console nor directly using cURL.

I am getting the deviation ID from the deviation's url:
![da - devid](https://cloud.githubusercontent.com/assets/2449542/17652397/291febee-6238-11e6-840b-87927d52933c.png)

It gives me a 404 when I use the web console, but it feels like a "this api is missing" 404:
![da - console](https://cloud.githubusercontent.com/assets/2449542/17652416/d6c977ba-6238-11e6-9c45-6fd7cae09615.png)

It gives me a 404 when I use cURL, and it's definitely an api missing 404:![da - curl](https://cloud.githubusercontent.com/assets/2449542/17652468/0e8f3bca-623a-11e6-8019-f2c3e80d5268.png)

I feel like that url has either broken or the documentation is incorrect.

**Comment by MahxieNoodle** [comment]
That is not the deviantid. It should look like AAAAAAAA-E303-BEF1-DE89-698B122667E3

![did](https://cloud.githubusercontent.com/assets/9665370/17652557/1df55eba-6234-11e6-8abd-fe8ede450137.png)

**Comment by Zeimyth** [comment]
Oh, okay, that would explain it. I didn't realize I should be looking for a UUID. Thanks!

Do you have any suggestions on the best way to go from a given deviation on the website to discovering the deviation ID? I would prefer to avoid having to pull a user's gallery and iterate through each item--potentially crossing several pages--in an attempt to find the json object whose url matches the url of the deviation.

**Comment by Zeimyth** [comment]
I found it. There is a meta tag on the deviation page. Thanks for pointing out my error.
