### ISSUE TITLE
Status items type documents : thumb_background_deviation

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#116]
Hi,
could you please provide documentation for statuses items types? currently it's undocumented string which is hard to predict, as I've currently faced previously unknown type: thumb_background_deviation.
What is it's meaning and difference from "deviation" type?
Are there any other? Currently I know of 3:
1) deviation
2) status
3) thumb_background_deviation

**Comment by muteor** [comment]
This seems to be used for adding previews to thumbnails of a status, I think you can probably safely skip those.
