### ISSUE TITLE
OAuth scope parameter for Client Credentials Grant

### ISSUE THREAD

**Issue by aycabta** [DeviantArt/DeviantArt-API#117]
I tried to use [`/user/whoami`](https://www.deviantart.com/developers/http/v1/20160316/user_whoami/2413749853e66c5812c9beccc0ab3495) with Client Credentials Grant, but response says "Expired oAuth2 user token. The client should request a new one with an access code or a refresh token". I thought that reason is the `scope` is not set. I set `scope` parameter for Client Credentials Grant, but response says "Scope has not been implemented, please remove it from the request". 

[The OAuth 2.0 documentation in DeviantArt](https://www.deviantart.com/developers/authentication) doesn't have `scope` parameter for Client Credentials Grant for sure.

Could I use `scope` parameter with Client Credentials Grant?

**Comment by redcapital** [comment]
Client Credentials give you access to public endpoints, i.e. where no user authorization is required. `/user/whoami` is not public, so you need to use Authorization Code grant, with `user` scope. See the OAuth page you linked for an example.

Also, each endpoint documentation page has an Authentication section, where you can see what kind of token and scopes you need.

**Comment by aycabta** [comment]
I understand. I'll use Authorization Code or Implicit. Thank you.
