### ISSUE TITLE
/collections/{folderid}

### ISSUE THREAD

**Issue by arthursteblin** [DeviantArt/DeviantArt-API#118]
Hi!

Today I found an incorrect API behavior. For example:

_GET https://www.deviantart.com/api/v1/oauth2/collections/DA1D523A-EAC0-972C-FB81-99D113195E94?username=ryky&offset=10&limit=10&mature_content=true_

If I understand correctly, the server should return an array containing 10 elements. In fact, it returns only 9 elements with the next offset 20. Is it the bug?

**Comment by muteor** [comment]
This is expected sometimes we filter out deviations for various reason, clients should respect the offset hints even if there are less items in the response.
