### ISSUE TITLE
Client Credentials for "public" endpoints

### ISSUE THREAD

**Issue by rAseri** [DeviantArt/DeviantArt-API#119]
Hi! 
I'am develop Android app for DeviantArt and faced with a problem: 
To get access to "public" endpoints my app should obtain access_token using "Client Credentials" flow.
According with "Client Credentials" flow, client make request using it's client_id and **client_secret**.
But OAuth specification says that public clients (Android app in my case) shouldn't store client_secret locally, because app can be decompiled and client_secret can be stolen. 

So, what the best way to store client_secret? I'm found this [answer](http://stackoverflow.com/questions/14570989/best-practice-for-storing-private-api-keys-in-android) and just to be sure i decide to place my question here. Thank you.

**Comment by muteor** [comment]
Yeah we accept that this is not ideal but you are fine to do what it says in that answer.
