### ISSUE TITLE
Documentation for pagination variations

### ISSUE THREAD

**Issue by KarsonKimbrel** [DeviantArt/DeviantArt-API#12]
I have noticed that 'delta' pagination as seen in the /stash/delta endpoint and the 'extended offset' pagination as seen in the /comments/deviation/{deviationid} endpoint are not included in the examples on the pagination documentation page.  I understand that these are minor variations, but I believe that the documentation would benefit for such an addition.  
Pagination documentation page: https://www.deviantart.com/developers/pagination

**Comment by muteor** [comment]
Fixed, thanks for the report.
