### ISSUE TITLE
/comments/deviation/{deviationid} 

### ISSUE THREAD

**Issue by arthursteblin** [DeviantArt/DeviantArt-API#120]
Hi, today I found another bug:

GET https://www.deviantart.com/api/v1/oauth2/comments/deviation/CC429983-0BCC-F240-BFB0-FB4D2E56EF28?commentid='43577390-D4A5-5C0F-C17F-34433AC4648D'

Response:
{
    "has_more": false,
    "next_offset": null,
    "has_less": false,
    "prev_offset": null,
    "thread": [
        {"commentid": "6D174318-AC19-3625-E2C9-DA8DDFB5300F",
            **"parentid": "43577390-D4A5-5C0F-C17F-34433AC4648D",**
            "posted": "2016-10-13T19:53:11-0700",
            "replies": 0,
            "hidden": null,
            "body": "Photoshop CC <img src=\"http://e.deviantart.net/emoticons/s/smile.gif\" width=\"15\" height=\"15\" alt=\":)\" data-embed-type=\"emoticon\" data-embed-id=\"391\" title=\":) (Smile)\"/>",
            "user": {
                "userid": "264A4B81-E65A-AC42-E236-248151768C49",
                "username": "TamberElla",
                "usericon": "http://a.deviantart.net/avatars/t/a/tamberella.jpg?1",
                "type": "premium"}}]}

So, I think, that the search should be performed by the key "commentid and not by key "parentid".

**Comment by Mr1Penguin** [comment]
It's not a bug. From console:

> Use `commentid` parameter to fetch replies to a specific comment.

**Comment by arthursteblin** [comment]
Well, I'm sorry, just it's not logical to me. Because sending key "commentid" I expect to get a result for this key.

**Comment by muteor** [comment]
Yeah thats just the way it is we wont be changing it now.
