### ISSUE TITLE
/user/friends/unwatch/{username}  method

### ISSUE THREAD

**Issue by Mr1Penguin** [DeviantArt/DeviantArt-API#121]
Hello! 
Request from title uses GET method but it used to change some data.
At the same time, request for start watching (watch/{username}) uses POST.
It's a mistake in description or it's really implemented this way?

**Comment by muteor** [comment]
The docs are correct, they are generated from the actual endpoints so all the core info should never be out-of-date. So yeah mistake in the implementation, would have been more logical for them both to be POST as they are write ops. I would change it but its been like that for a while so clients already depend on it.
