### ISSUE TITLE
Scope for group API endpoints

### ISSUE THREAD

**Issue by sontat** [DeviantArt/DeviantArt-API#122]
Hello,
Although there isn't any documentation for group API endpoints, GET /group/profile/{groupname} seems to be implemented, but requires a scope other than browse or user. What scope is required to access group API endpoints, and if group API is not supported yet, is there an estimate of when it will be supported?

**Comment by muteor** [comment]
Good find but the group endpoints were never finished so while they sort of exist they dont actually work.

No plans afaik to finish them either sorry.
