### ISSUE TITLE
DeviantArt Search API

### ISSUE THREAD

**Issue by ilovepumpkin** [DeviantArt/DeviantArt-API#130]
I am trying to build an app using DeviantArt API. Now I want to implement a search UI - display the thumbs first, then display more information about the deviation if users click the thumb (using the API https://www.deviantart.com/developers/http/v1/20160316/deviation_single/bcc296bdf3b5e40636825a942a514816 ). Currently it seems that the only way to do this is to use RSS feed - "https://backend.deviantart.com/rss.xml?type=deviation&q=by:ilovepumpkin2014 sort:time meta:all searchKeyword", but the problem is that in the returned XML document, I can not get the id of each deviation. Is there any way to solve this problem? Is it possible to contain the deviation id in the returned RSS XML result ? Or are there any other APIs can make this work ?

**Comment by zsgalusz** [comment]
You can search using the q parameter of the browse endpoints: https://www.deviantart.com/developers/http/v1/20160316/browse_newest/81c87f79a46989ee63bca2f70e4ca0fc

**Comment by DineshSolanki** [comment]
Now that deviantArt has removed browser/popular and newest endpoints, does anybody have anything else in mind
