### ISSUE TITLE
Cannot grant "browse" scope on new authorizations

### ISSUE THREAD

**Issue by SeinopSys** [DeviantArt/DeviantArt-API#133]
Here's my exact authorization URL: https://www.deviantart.com/settings/applications?state=%2F&scope=user+browse&redirect_uri=https%3A%2F%2Fmlpvc-rr.lc%2Fda-auth&response_type=code&client_id=2786 (Note: `redirect_uri` points to my local testing domain, it won't load an actual page after authorizing)

Note the `browse` in the `scope` parameter, yet the page does not display the bullet point for "Browse public information" nor will the token have that scope set once I get a response from the API.

Personally I'd be the happiest if `user/whois` did not require the `browse` scope and could be used with a simple client access token, but if the scope is a must-have requirement then please make sure I can actually request that scope from the users.

**Comment by Mr1Penguin** [comment]
Try to use https://www.deviantart.com/oauth2/authorize instead of  https://www.deviantart.com/settings/applications.
First one redirects user to second one but with updated scope.

**Comment by SeinopSys** [comment]
I am actually using that, I just grabbed the URL from the browser which was visible after the redirection.
