### ISSUE TITLE
Upload fails: internal server error

### ISSUE THREAD

**Issue by mardy** [DeviantArt/DeviantArt-API#134]
Hi there!
  I'm writing an application to upload images to deviantart; the authentication step goes fine and I can receive the access token, but when I try to upload a photo to `stash/submit` I get this as reply:
```
{"error":"server_error","error_description":"Internal Server Error.","status":"error"}
```
Is the server down, or could the problem be due to my request? And could the error message be made more helpful?

**Comment by mardy** [comment]
Found out the issue: it's necessary to specify the file name of the uploaded file.

**Comment by ananmelkonyan** [comment]
Can you please provide some code i am getting that problem too. @mardy

**Comment by mardy** [comment]
@ananmelkonyan When building the form-data request, make sure you inglude both the `filename` and `name` parameters, like this: https://stackoverflow.com/a/46150309/6113088

If you are doing that already, then your problem is probably different, and I cannot be of help. :-)

**Comment by ananmelkonyan** [comment]
@mardy thank you for quick reply, 
here my debug array
`Array
(
    [title] => test file
    [artist_comments] => 1
    [file] => CURLFile Object
        (
            [name] => zebra_8.jpg
            [mime] => image/jpeg
            [postname] => zebra_8.jpg
        )

    [access_token] => access_token
)`
if your code php can you provide more details? :)

**Comment by ananmelkonyan** [comment]
@mardy or if you can provide me request build part

**Comment by mardy** [comment]
Sorry @ananmelkonyan, my code is in C++/Qt, so I'm afraid it wouldn't be of help.

**Comment by ananmelkonyan** [comment]
Dear @mardy its ok i can read c++, need just see configuration on file output, i followed your suggest but its throw me server error.
