### ISSUE TITLE
RSS API: deviant nick start with an extra /  

### ISSUE THREAD

**Issue by shiyunhe** [DeviantArt/DeviantArt-API#135]
All the deviant nick names now have an extra /

**Comment by zsgalusz** [comment]
Where do you see this? Can you post an example? eg. I looked at https://backend.deviantart.com/rss.xml?q=boost%3Ahot+meta%3Aall&type=deviation and I don't see any extra slashes in the author names.

**Comment by shiyunhe** [comment]
An author's nick name is extracted from <guid XML element. The link used to be http:// and now it has changed to https://. The code in my app is hard-coded, so an extra / is produced.

I am sorry to bother you for the issue.

**Comment by zsgalusz** [comment]
Yeah we switched everything to https now so you should update all parsers to that.
