### ISSUE TITLE
token?grant_type=refresh_token requests always returns a new refresh_token

### ISSUE THREAD

**Issue by Mr1Penguin** [DeviantArt/DeviantArt-API#136]
Whenever I do request
`https://www.deviantart.com/oauth2/token?grant_type=refresh_token&client_id=1234&client_secret=123abc&refresh_token=myrefreshtoken` there is always different refresh_token in response json.

Is there any workaround on client side to not change refresh_token while getting new access_token?

**Comment by zsgalusz** [comment]
Refresh tokens are intended to be single use, so there is no workaround.
