### ISSUE TITLE
API rate limiting should return 429 responses with JSON body instead of 403 and HTML

### ISSUE THREAD

**Issue by SeinopSys** [DeviantArt/DeviantArt-API#143]
I'm assuming I'm being rate limited by the API because requests that were previously successful are now giving me 403 pages, but the library I'm using to access your service chokes because it expects JSON responses and not HTML.

**Comment by Mr1Penguin** [comment]
Are you using the same token in both cases?

**Comment by KarsonKimbrel** [comment]
I believe DA has responded to this in the past. If I remember correctly, they said it is because of the load balancer responding with a 403. I think DA's advice with non 200 responses is to treat them as errors.

**Comment by SeinopSys** [comment]
That's not exactly surprising given their design decision track record, but I'd still say a 403 response is an awfully unhelpful response when being rate limited, load balancing or not. How's someone supposed to differentiate between an invalid access token and rate limiting?

**Comment by KarsonKimbrel** [comment]
The error message provided.

**Comment by KarsonKimbrel** [comment]
If you are getting an HTML response back as opposed to a JSON response, ensure you are sending an useragent with your request.
See 403 errors: https://www.deviantart.com/developers/errors

**Comment by SeinopSys** [comment]
For the record, the 403 responses were temporary and came after I had made a lot of requests due to a programming error on my end, The same exact code making the same exact requests just now works as expected. I have always been sending a user-agent header and the compression header because without them the API don't even accept the request normally.
