### ISSUE TITLE
How to batch edit deviations (not stashs) by API?

### ISSUE THREAD

**Issue by stonyau** [DeviantArt/DeviantArt-API#148]
For a very long while I have been posting staffs to Deviantart by API. There were 2 steps, as we all know.

1. Submit stash
2. Publish stash to Deviantart

Now, I wanted to batch edit my deviations. I read over the API doc but I could not find an endpoint to edit deviations. I tried to create new stash with the same content and submit again. Clever enough, the API returned an error "Deviation already published".

Please Deviantart help me on this, this is important to me.

**Comment by muteor** [comment]
See https://www.deviantart.com/developers/console/stash/stash_submit/0f1832daa6b58a05841ec6058520c4f3

This has `itemid` which can be used to update a submission: 

The id of an existing Sta.sh submission. This can be used to overwrite files and /metadata of existing submissions. If you make a new API call containing files, the files that were previously associated with the artwork will be replaced by the new ones.
