### ISSUE TITLE
Prove relationship to the original DeviantArt content and brand

### ISSUE THREAD

**Issue by abdoulayeYATERA** [DeviantArt/DeviantArt-API#149]
Hi,

I use DeviantArt Apis in my Android app (client id: 3729), however the Google Play policy needs me to prove my relation with DeviantArt.

Can i have such a document?

Thank you very much.

This is the exact message from Google:

------------

Hi,

Thank you for reaching out to the Google Play team.

After reviewing your attachment, we were still unable to validate your account's relationship to the original content or brand owner. Please provide verifiable documentation of copyrighted content with the following examples: distribution agreement, authorization contract, or website domain ownership (PDF file). Please reply to this email with the documents attached.

I look forward to hearing back from you.

**Comment by KarsonKimbrel** [comment]
To my knowledge, your relationship to deviantArt is solely what is inside of the ToS and Developer Agreement on deviantART's website.

**Comment by abdoulayeYATERA** [comment]
Absolutely, however what they are looking for is a document mentioning my DeviantArt developper account as allowed to use DeviantArt api and content.
A shield against copyright issue with DeviantArt i guess...

**Comment by abdoulayeYATERA** [comment]
I understand their point of view but very annoying for me..... maybe someone can unlock the situation here.

**Comment by KarsonKimbrel** [comment]
https://about.deviantart.com/policy/api/
Particularly, I think you want to look at point 6.

**Comment by KarsonKimbrel** [comment]
Additionally it may be beneficial to provide your app's dA listing.
https://www.deviantart.com/apps/newest/

**Comment by abdoulayeYATERA** [comment]
Thank's for you ideas, unfortunately that's not ok, my app is still suspended.... they want a document saying that my app (id=com.yadevapp.dnart) is a known and authorized app by DeviantArt.
