### ISSUE TITLE
Manage notes in a personal client

### ISSUE THREAD

**Issue by c-chell** [DeviantArt/DeviantArt-API#152]
Hello,

I want to create a client that use the API https://www.deviantart.com/api/v1/oauth2/notes (and all of its derivative) to manage only my notes.

I think I need to have an API KEY or something like that, to do it outside my logged session on DeviantArt (on a remote server).

I only want to know what I need to do to manage my notes (and only my notes by a private application).

Thank you.

**Comment by kervala** [comment]
You just need to read the documentation :p https://www.deviantart.com/developers/

**Comment by kervala** [comment]
You need to call OAuth2 authentication : https://www.deviantart.com/developers/authentication

First you need to authorize your application :
https://www.deviantart.com/oauth2/authorize?response_type=code&client_id=<your client id>&redirect_uri=https://your_url&scope=note

You'll receive a "code" parameter to your redirection URL.

Then to get your token :
https://www.deviantart.com/oauth2/token?client_id=<your client id>&client_secret=<your client secret>&grant_type=authorization_code&code=<your code received from previous call>&redirect_uri=<same redirect url as previous call>

You'll get your access_token in JSON :
`{
  "expires_in": 3600,
  "status": "success",
  "access_token": "Alph4num3r1ct0k3nv4lu3",
  "token_type": "Bearer"
  "refresh_token": "3ul4vn3k0tc1r3mun4hplA",
  "scope": "basic"
}
`

**Comment by kervala** [comment]
If you don't want to publish your application, you just don't put any link to your site/application ;p

**Comment by c-chell** [comment]
Thank you, with your help now I can do it.
This is the first time I need this kind of thing and the pattern to access to the data is not simple for me.

With your help, now I can move further, thank you :)

**Comment by kervala** [comment]
You're welcome :) Good luck with your project :)
