### ISSUE TITLE
Cropped Thumbnails

### ISSUE THREAD

**Issue by abdoulayeYATERA** [DeviantArt/DeviantArt-API#154]
Hello, I just notice that some deviation thumbnails were strangely cropped.
For exemple:
https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/intermediary/f/6f131d22-7974-4793-9db3-2160376b5c72/d9kmnxu-43ae474c-27a1-424c-993c-e2cbb705eb6e.jpg/v1/fill/w_300,h_900,q_70,strp/guard_by_wlop_d9kmnxu-300w.jpg

deviation id : 25ECCFD6-1B64-6F44-4E96-FF50CA644E97

**Comment by muteor** [comment]
Thanks will check it out.
