### ISSUE TITLE
how can i drag random picture by using your api ?

### ISSUE THREAD

**Issue by andermirik** [DeviantArt/DeviantArt-API#159]
i can download images from here  [https://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+overwatch](https://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+overwatch)
but i don't know how many items/images are there

**Comment by mircodezorzi** [comment]
As the API developers don't seem too active I'll take the liberty to answer this question:

If your intent is to only get the amount of results from a search you can parse the response of the http search page, unfortunately I'm afraid this is the only easy way to do it... 

Here's a python snippet:
```python
import requests
import re
r = requests.get("https://www.deviantart.com/search?q=overwatch")
print(re.findall('<span class="_1vwpS">(.*?) results</span>', r.text))
```

If, on the other hand, you want to download all of the pictures from the feed you can use the `offset` and `limit` parameters to scroll thought it.

**Comment by zsgalusz** [comment]
Our RSS API doesn't have total numbers. So you will either need to page through the results until no more is returned, or use our oAuth API which does return the approximate number of results in the response.

**Comment by andermirik** [comment]
May you add some SELECT COUNT(*) FROM some_table WHERE tag = q ?
