### ISSUE TITLE
API does not download full size GIF images with previews

### ISSUE THREAD

**Issue by merberich** [DeviantArt/DeviantArt-API#160]
Via the DA API's `GET /deviation/download/{deviationid}` for deviations that are GIF images with previews, the result `src` will be the preview image instead of the full-size image. I have confirmed this in the in-DA console as well.

Steps to repeat:
1) Use the API download for deviation ID "8C5FD685-A71E-2290-1E60-F6A4927DE4BD".
2) Observe the reported download dimensions of (253h,450w).
3) Navigate to `src`.
4) Observe the actual source dimensions are clearly smaller (this matches the preview dimensions).
5) Navigate to the [deviation page](https://www.deviantart.com/arsenixc/art/city-test-II-356750477).
6) Click the "Download" button.
7) Observe that the downloaded source dimensions match the reported dimensions.

This seems erroneous... I would expect the API deviation download functionality to be identical to the in-browser download functionality.

**Comment by zsgalusz** [comment]
Thanks for reporting! Will look into it.

**Comment by zsgalusz** [comment]
Should be fixed.
