### ISSUE TITLE
/deviation/download/{deviationid} not working

### ISSUE THREAD

**Issue by demenf** [DeviantArt/DeviantArt-API#161]
Hello!

The URL of that endpoint returns a 404 error. For example:
https://www.deviantart.com/cryptid-creations/art/Daily-Paint-2502-Desert-Tortoise-814769016

If I click the Download button the image downloads. So the download capability is ok.

But... That endpoint returns this object (tested with [online console](https://www.deviantart.com/developers/console/)):
```json
{
    "src": "https://fc04.deviantart.net/wixmp/f/885a6dec-35b8-456f-a409-43b214729c22/ddh3bso-cd062ce6-4e1d-4e5c-8e6b-aaf740baf5a7.png?st=*******&e=******",
    "width": 850,
    "height": 627,
    "filesize": 582346
}
```
Following the link I get this 404 URL: https://orig01.deviantart.net/f70b/f/885a6dec-35b8-456f-a409-43b214729c22/ddh3bso-cd062ce6-4e1d-4e5c-8e6b-aaf740baf5a7.png

Deviation UUID: F2485325-ED53-AAC7-629B-7794D7671152

**Comment by zsgalusz** [comment]
Thanks for reporting, will look into it.

**Comment by Archirk** [comment]
Yep. Same issue. Method returns URL for download but link returns 404.
UUID example:  12D85416-1CD0-3D3A-CC28-A789AC89F4D4

**Comment by zsgalusz** [comment]
Should be fixed.

**Comment by 0xE1** [comment]
Server that serves "src" url is missing content-length header =\

**Comment by KarsonKimbrel** [comment]
You may want to open a separate ticket for that.
