### ISSUE TITLE
oAuth login does not redirect

### ISSUE THREAD

**Issue by Kyttias** [DeviantArt/DeviantArt-API#162]
Preface - Hello! Last year before Eclipse rolled out I made an app with dA's official Developers API, where users sign in using oAuth2. I'll start by saying I did not experience this issue last year before Eclipse changed the look of the login window.

What is the issue? - After my app redirects the user to dA to verify the connection end point, they are presented with a "Join DeviantART" screen rather than a log in screen. This is the same as last year, however -- when users press "Log in" next to "Already a deviant?" the redirect uri vanishes from the url -- causing them to go directly to DeviantART instead of back to my app they were trying to make a connection to. If they manually type in my url again, their account is in fact connected.

I'm sorry I may be one of the only people on the planet actually trying to use dA's oAuth API so my users can log in with their dA accounts, but this is for an event for a dA group, so... a working log in screen would be nice. I can instruct users they'll have to manually re-enter the url after logging in, but, that's really confusing for them. It redirected just fine last year.

The event I'm using the oAuth API for only runs until the end of October. For now I will simply tell my visitors that due to a glitch on DeviantART's end, they are no longer redirected after sign in.

(In addition by saying that the new Eclipse oAuth log in screen looks kinda janky in mobile/responsive browsers (it's too tall and unscrollable). My site operates in landscape mode, so users will have to rotate to sign in, and then rotate back to continue on.)

**Comment by SeinopSys** [comment]
I'm getting the same issue, tried to email their support but they said to "contact the developers directly" on here. I'll be damned before I find a single recent developer response in this repository.

**Comment by Kyttias** [comment]
Haha, same. I also contacted their support team first and was also directed here. In a lot of ways, the API hasn't been touched since the Eclipse team took over -- and they were the ones who broke this.

**Comment by zsgalusz** [comment]
We are actually working on a fix for this right now! Will mention the landscape issue to the team, too.

**Comment by SeinopSys** [comment]
Color me impressed, I thought this place was no longer monitored.

**Comment by Kyttias** [comment]
I can't thank you guys enough. My event goes live for my group on the 17th and only runs through Halloween (trick or treating themed). Even if this doesn't see a fix that fast, it's a good sign and I'm looking forward to continuing to use the API for future projects. (Unrelated -- I wish there were more group-related features the API could cover - what groups a user is in, for example. And for oEmbed to detect what groups a deviation has been submitted to, etc. I have to use some really tedious work arounds for those, and I'm not sure where I should go to plead for additional functionality? )

**Comment by zsgalusz** [comment]
Regarding adding new functionality to the API - right now we don't have active development on new features, hopefully once the dust with Eclipse settles we can get back to it. Groups-related data are particularly troublesome because they are a major resource hog to fetch - so wouldn't want to just add something half-baked that then brings the entire API down.

**Comment by muteor** [comment]
This should be working as normal again.
