### ISSUE TITLE
user/watchers/{username} - Internal Server Error

### ISSUE THREAD

**Issue by parallellogic-** [DeviantArt/DeviantArt-API#19]
When accessing offset 209,200 of yuumei's watchers, the endpoint produces an "Internal Server Error"
http://i.imgur.com/5xKGmTx.png

At time of writing (Reedoh is the most recent watcher at offset 0), there appears to be some error with user #209217 specifically.  If I set the offset to "209217" and limit to "1", I receive an internal server error.  If I query the users ahead and behind: offset=209166, limit=50 or offset=209218 limit=50, I do not receive an error.  The error only appears when the query includes user #209217.

**Comment by KarsonKimbrel** [comment]
I think dA may have already fixed this bug.

I tried to reproduce and I found that yuumei has no friends at that offset:
{
    "has_more": false,
    "next_offset": null,
    "results": []
}

The last offset I found users at was 200 with a limit of 50:
{
    "has_more": false,
    "next_offset": null,
    "results": [
        {
            ...
        }, 
        ...
    ]
}

**Comment by KarsonKimbrel** [comment]
I have reproduced this at offset 209400.

**Comment by muteor** [comment]
Fixed
