### ISSUE TITLE
dA uses HTTP 403 Forbidden as HTTP 429 Too Many Requests

### ISSUE THREAD

**Issue by KarsonKimbrel** [DeviantArt/DeviantArt-API#20]
You can reproduce this using any endpoint but for this I made many calls to /user/damntoken in a short amount of time.  Instead of giving a 429 to signal the rate limit has been exceeded the server will incorrectly send a 403.  This contradicts the error documentation: https://www.deviantart.com/developers/errors .

GET https://www.deviantart.com/api/v1/oauth2/user/damntoken?access_token=XXXXXX

HTTP/1.1 403 Forbidden
Cache-Control: no-cache
Content-Type: text/html
Date: Sun, 04 Jan 2015 20:32:38 GMT
Server: ECD (cpm/F82C)

**Comment by muteor** [comment]
Do you know how many requests per second you were doing?

**Comment by KarsonKimbrel** [comment]
Give me a moment and I'll see.

**Comment by KarsonKimbrel** [comment]
18 successful requests in 6.059 seconds before it gave a 429.

**Comment by muteor** [comment]
Ok thanks, the error is coming from our CDN I will investigate further in the week.

**Comment by KarsonKimbrel** [comment]
Alright, thanks!

**Comment by muteor** [comment]
Did the response contain any body? Would help us to determine where the error is coming from.

**Comment by KarsonKimbrel** [comment]
I was unable to get a body, so I am fairly certain there was none, just a header.

**Comment by muteor** [comment]
The 403 error is being returned from our load balancers, the error for now should be treated the same as a 429 and the client should back-off. We will be updating the load balancers to return proper 429 errors at some point in the future. I will add a note to the docs later, thanks for the report.

**Comment by KarsonKimbrel** [comment]
Alright, thanks for the quick response.
