### ISSUE TITLE
user/whois - Expired oAuth2 user token

### ISSUE THREAD

**Issue by parallellogic-** [DeviantArt/DeviantArt-API#22]
I query the user/whois endpoint as follows:
https://www.deviantart.com/api/v1/oauth2/user/whois?%22usernames[0]=parallellogic%22&access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
The returned response states I have an "Expired oAuth2 user token. The client should request a new one with an access code or a refresh token."
I subsequently query the util/placebo endpoint and I receive a "success" response.  I expected that if the util/placebo endpoint returned a success that the user/whois endpoint would behave as documented.

Also, it is unclear in the user/whois documentation how to query multiple users - whether we should query as "usernames[0]=parallellogic&usernames[1]=spyed" or some other format is not specified.

**Comment by KarsonKimbrel** [comment]
Make sure you're using an authorization code or refresh token granted access_token.

**Comment by KarsonKimbrel** [comment]
Also the usernames param should be sent in the http body as post data.

**Comment by muteor** [comment]
Multiple users are queried using an array via post and the endpoint does not support client credentials. I might change that when we get around to refactoring the whoami and whois endpoints.
