### ISSUE TITLE
GET /feed/home

### ISSUE THREAD

**Issue by shiyunhe** [DeviantArt/DeviantArt-API#23]
The end point still returns "has_more " = 1 at the end of the feed.

{
    cursor = MD0wJjE9MjkmMj0xOSYzPTAmND0wJjU9MCY2PTAmNz00Jjg9MCY5PTAmMTA9MTAmMTE9MCYxMj0wJjEzPTAmMTQ9MCYxNT0wJjE2PTAmMTc9MCYxOD0wJjE5PTAmMjA9MCYyMT00JjIyPTA;
    "has_more" = 1;
    items =     (
    );
}

**Comment by muteor** [comment]
This should now be resolved.
