### ISSUE TITLE
"/user/whois" Error

### ISSUE THREAD

**Issue by metinmete** [DeviantArt/DeviantArt-API#25]
"**/user/whois**" not work or i'm making a mistake.

https://www.deviantart.com/api/v1/oauth2/user/whois?usernames[]=xxx&access_token=xxx

```JSON
{
error: "invalid_request",
error_description: "Request field validation failed.",
error_details: {
usernames: "usernames is required"
},
status: "error"
}
```

And why don't the number of members in the group statistics?

**Comment by muteor** [comment]
The endpoint is POST only and we will be looking at groups at a later time.
