### ISSUE TITLE
GET /browse/popular limit

### ISSUE THREAD

**Issue by shiyunhe** [DeviantArt/DeviantArt-API#29]
limit parameter used to be 120. Now it becomes 24 and breaks my app due to field validation.

{
    error = "invalid_request";
    "error_description" = "Request field validation failed.";
    "error_details" =     {
        limit = "limit is not within the allowed range";
    };
    status = error;
}

Is it possible to make a new version instead of breaking my app. I guess there are other endpoints broken due to limit changes.

I would appreciate it if this can be fixed quickly.

Thanks in advance.

Regards,

Yunhe

**Comment by muteor** [comment]
Sorry forgot about versioning the change, will revert for now.

**Comment by shiyunhe** [comment]
Thanks for quick response
