### ISSUE TITLE
Suggestion: Change logs of different API version

### ISSUE THREAD

**Issue by shiyunhe** [DeviantArt/DeviantArt-API#30]
It would be helpful to have a change log of different version so that it is easy to migrate to new version.

**Comment by KarsonKimbrel** [comment]
I too would like to see this change.  At the present time, i feel that the change log in its current state of info is insufficient.

**Comment by muteor** [comment]
We have updated the changelog to be "semi automated" so hopefully we will not forget to update it. 

https://www.deviantart.com/developers/changelog

Not all versions are listed as some are/were made for features that are not public.
