### ISSUE TITLE
Using The Client Credentials Grant is not working

### ISSUE THREAD

**Issue by MonsterMMORPG** [DeviantArt/DeviantArt-API#32]
Hello. Now when i logged in browser i am able to get

User Authorization and with it i am able to submit art to my gallery via curl command

However what i want to achieve it without browser login

So i am getting access token with

https://www.deviantart.com/oauth2/token?grant_type=client_credentials&client_id=MYID&client_secret=MYSECRET

However this time this access token fails when i try to submit to my stash via curl

it tells me that "expired auth2 user token" however i just got it

How can i solve this problem ? Can't i grant myself to submit my own stash without logging in deviantart ?

thank you

**Comment by KarsonKimbrel** [comment]
You cannot, use an authtoken obtained with the client credentials grant to submit or publish art on the behalf of a user.

**Comment by MonsterMMORPG** [comment]
But it requires browser login. Any way to obtain it without browser login ?

Why can't we supply username and password to obtain it ?

I want to upload my own stash not any other member stash

**Comment by MonsterMMORPG** [comment]
And is it possible to obtain authtoken longer than 1 hour ? like 1 day or
like 30 day or permanent ?

ty

**Comment by KarsonKimbrel** [comment]
No.  You must obtain an user authtoken with the stash grant (and possibly the publish grant if you are using the /stash/publish call).  Also no, you must use the refresh token once the token expired.

**Comment by MonsterMMORPG** [comment]
1 more final question

lets say i obtained token

but it expired after 2 hours

do refresh token works still ?

also can i permanently use refresh tokens without asking authorization
again ?

**Comment by KarsonKimbrel** [comment]
https://www.deviantart.com/developers/authentication#refresh

**Comment by KarsonKimbrel** [comment]
Also, http://tools.ietf.org/html/rfc6749 .

**Comment by MonsterMMORPG** [comment]
from this description "All access_token's expire after one hour, after
expiration you either need to re-authorize the app or refresh your access
token using the refresh_token from the /token request. "

i understand that i can use it permanently without asking re-authorize
again am i right ?

ty very much

**Comment by KarsonKimbrel** [comment]
It is possible for the access token to invalidate.  You should follow the directions of the error returned if the refresh token invalidates.

**Comment by muteor** [comment]
Thanks for helping with that Karson :) Think all questions were answered so closing.
