### ISSUE TITLE
Do deviantart have stash folder size?

### ISSUE THREAD

**Issue by MonsterMMORPG** [DeviantArt/DeviantArt-API#35]
From api when i list inside a folder with the following way

"https://www.deviantart.com/api/v1/oauth2/stash/metadata?list=1&folderid=" + srFolderid + "&access_token=" + srAuthCode;

I don't see offset. So does this mean there is no folder size limit and api displays all results ?

So far i tried with 132 items and it listed all items

**Comment by muteor** [comment]
Yeah there is no limit on that at the moment. We want to go back at some point and update the entire stash api so that its a bit more sane, we are just waiting for time to do it.
