### ISSUE TITLE
Scope level error

### ISSUE THREAD

**Issue by MonsterMMORPG** [DeviantArt/DeviantArt-API#36]
I have authorization scope : &scope=stash publish

Which i believe highest possible am i wrong ?

However this basic command : https://www.deviantart.com/api/v1/oauth2/gallery/folders?username=monstermmorpg&calculate_size=1&access_token=mytoke

fails : {"error":"insufficient_scope","error_description":"The requested resource requires a higher scope than the user has allowed the client to access, client needs to re-authorize.","scope":"browse","status":"error"}

Isn't this an error ?

**Comment by muteor** [comment]
The error includes the scope you need, in this case that is "scope":"browse", so you need to request to browse scope.
