### ISSUE TITLE
Suggestion: Categories list for offline usage

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#38]
Hi there, it would be really nice to be able to get all the hierarchy for offline usage so that not to call it every time from the server. As for now I tried to get it through recursive "get" calls, but unfortunately soon get 403 as it seams to many calls at a time.

**Comment by shiyunhe** [comment]
I agree that API should provide an option to return all categories in one API call so that an app can cache categories for off-line use.

**Comment by KarsonKimbrel** [comment]
The 403 is a bug with their load balancer as I understand, you should treat it as a 429 (rate limit exceeded) and slow down your requests.  You can easily get all of the categories and cache them in the call's current state.

**Comment by Viachaslau-Zinkevich** [comment]
I do understand the 403 code, but imagine making user wait both for recursive download and cooldown. It will take quite the time

**Comment by muteor** [comment]
The category tree is very large about 4k individual categories, we cant produce that efficiently enough to return the entire tree in one go, it would also be a huge json object for you to handle. Hopefully one day we will get time to really address the category system as a whole, until then we are stuck with what we have.

With the 403 errors, we are working on getting them changed to 429s. But you also need to make sure that you are sending a user-agent and have compression enabled, doing that should eliminate your 403 problems.

**Comment by shiyunhe** [comment]
4k is a small size. Usually a full size image is about 50k - 200k. The end point won't be called frequently. If a last updated date can be provided by the end point, a client app only need to update the category when needed. One of my apps parses 500 photos with a json file size (250k - 350k) and works fine. I still hope that the entire category tree can be returned with one call.

**Comment by Viachaslau-Zinkevich** [comment]
I thinks it's not the size in bytes but the count of categories

**Comment by shiyunhe** [comment]
One solution is to provide a link to a static json file. There will be very little impact to the server. You can generate the json file when categories changes.

**Comment by Viachaslau-Zinkevich** [comment]
Actually nice idea...
