### ISSUE TITLE
Suggestion: Add 'type' parameter to user/whoami response

### ISSUE THREAD

**Issue by KarsonKimbrel** [DeviantArt/DeviantArt-API#4]
I would like to request the addition of the 'type' parameter (as seen in the /user/whois user object).  I would like to request this so that I don't need a unique object to store the authenticated user's info in.  Also, it just feels like the 'type' parameter belongs in the /user/whoami call.  
~baronbeandip~

**Comment by muteor** [comment]
We will be refactoring the whoami endpoint art some point to use the standard user object. No eta yet.

**Comment by muteor** [comment]
We have updated this now and from version 20150106 whoami returns the standard user object.
