### ISSUE TITLE
Empty preview for "is_downloadable": false

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#43]
When getting deviations with field "is_downloadable": false the Preview field is empty even having thumbs filled. Is it expected behavior and what are the ways to at least show the deviation in a little bit bigger format then preview?

**Comment by muteor** [comment]
You got any examples?

**Comment by Viachaslau-Zinkevich** [comment]
Mmm, I've noticed now that's actually Preview missing not only for is_downloadable:false, but some others,too. Example dev.id: C6432E08-33C1-7B38-B75E-358225419192. I've also noticed the content dimension isn't too big, could it be the reason for missing Preview, when the content itself isn't big?

**Comment by muteor** [comment]
Yes, we don't generate a PRE for "small" images, not sure what the threshold is though. So you need to check for both, pre will be smaller than content. We need to document this better probably, deviations are very complex with lots of types etc. Take a look at the docs for the response here https://www.deviantart.com/developers/http/v1/20150217/object/deviation anything marked optional should always be treated as so in your code.
