### ISSUE TITLE
More from this author behavior

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#46]
I found that to get more from this author preview you use morelikethis/preview and to get morelikethis all data you'd use /morelikethis. But what is the way to get full data for More from this author? Is there any way to do this besides scanning each and every collection of the user?

**Comment by galymzhan** [comment]
/preview returns up to 24 author deviations. If you want more, you have to load them from the author's galleries

**Comment by Viachaslau-Zinkevich** [comment]
Thanks a lot!
