### ISSUE TITLE
Deep link fron Journal deviations

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#47]
As I understood, I need to display the data of journals as html. The question is, if there a way to get deviation Id from link, may be? For example, if in an Android app I click a link in a journal -- the deviation will be opened in application, not in browser. How can this be achieved? 

And what does exactly do /embeddedcontent? I thought it would return all the deviations inside the journal, but as far as I saw -- it doesn't, but has a lot of other different deviations, which I can't connect to each other.

**Comment by muteor** [comment]
This is what I as talking about in the previous issue, we are working on making it easier to handle these links.

The /embeddedcontent endpoint fetches deviations inside a journal, its highly dependent on the markup of the journal though, so only picks up things embedded using stash writer.
