### ISSUE TITLE
Video source url while using Client Authentication

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#48]
It seams that URL generated specifically with Client authentication request is somehow bad, as it results in always redirecting to the deviation page, not to the real video url. 
Steps to reproduce: 
1) Get deviation with videos authenticating with client token
2) Request through both browser and code Video
3) Be rediredicted to html page

While using User authentication:
1) Get deviation with videos authenticating with client token
2) Request through both browser and code Video
3) Get Http Response with 302 code and Location header set to video file.

I think that expected result for the first situation is the same as the second one.

**Comment by muteor** [comment]
Yeah videos were using the wrong url, have updated so that the correct ones are sent. This change wont be immediately available so should come through in the next day or so.
