### ISSUE TITLE
Ocasional 404 while calling /token or other endpoints

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#50]
Would you be so kind to investigate the reason, why sometimes on working urls 404 is returned. I know the urls are valid as getting the exception I try it in browser -- and result is returned successfully. One example is getting client_credentials token returns 404.

**Comment by galymzhan** [comment]
Are you sure these are 404 and not 400? Any other affected endpoints?

**Comment by Viachaslau-Zinkevich** [comment]
I'm pretty sure, as I get exactly 404. Unfortunately, I haven't logged urls until recently, but I did get quite a few 404 exceptions even though resources are available.

**Comment by muteor** [comment]
We haven't had any similar reports, would need detailed request/response logs to help debug. I usually use mitmproxy (https://mitmproxy.org) to debug stuff like this or wireshark etc.

**Comment by Viachaslau-Zinkevich** [comment]
I'll try to reproduce, but this url https://www.deviantart.com/oauth2/token?grant_type=client_credentials&client_id=ID&client_secret=SECRET causes 404 definitely.

**Comment by shiyunhe** [comment]
I did see occasional 4xx issue to various endpoints. Reloading the same endpoint seemd to work OK. It is a tricky issue to reproduce in order to fix it.

**Comment by muteor** [comment]
That url is working for me. I actually have tests that run ever 15 minutes all using that endpoint for their tokens, I would expect those to fail also if there was an issue.

Could you be hitting the clients rate limit maybe and getting a 429 or 403 error?

**Comment by Viachaslau-Zinkevich** [comment]
I'm sure it's not that kind of errors. As far as I see, it may be the framework problem to show 404 when the internet connection is not available. But I've also seen the behavior while having connection but with other urls, like curated tags. As for now I'll close the issue then. Thanks for the help.
