### ISSUE TITLE
Login without navigating to browser page

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#51]
Hi, I almost certain that this is not possible unless the app is yours by nature and is trusted, but still I'd like to ask if there a way to login through custom native controls like textbox/buttons without necessity to show the deviantart.com login page?

**Comment by KarsonKimbrel** [comment]
Pickley did this for his Stasher app, by page scraping I am pretty sure.  I would not advise doing this; just use the OAuth2 login provided by dA.  That is how OAuth2 is supposed to be used, you should never modify the login page.  If you would like a way to use your own login screen I would suggest lobbying dA to allow for xAuth.

**Comment by Viachaslau-Zinkevich** [comment]
Well, I definitely don't want to scratch anything from the site as it's a really uneasy, I think even insecure and illegal way to use API. I'd surely prefer official way to do this or otherwise, of course, through OAuth2 way using web page. I just wonder how the official apps do this without web views.

**Comment by muteor** [comment]
We wont provide this type of authentication because we need to guarantee correct permissions are displayed and that all the correct terms and conditions are accepted. Also for third-party apps we need the user to be able to see that the app accessing their account is NOT an official client.
