### ISSUE TITLE
Internal Server Error for /deviation/whofaved

### ISSUE THREAD

**Issue by parallellogic-** [DeviantArt/DeviantArt-API#52]
I call the following endpoint with my access token:
https://www.deviantart.com/api/v1/oauth2/deviation/whofaved?deviationid=AFB385A6E4CA977B47BA41A7D31EADC3&offset=2700&limit=50
I receive:
{"error":"server_error","error_description":"Internal server error."}
Upon checking the favs of this deviation, I see that there is a "Nobody" record:
http://www.deviantart.com/deviation/33899945/favourites?offset=2700
on that page.  I would like to get the remaining 49 favs from that page rather than a server error.
![deleteme](https://cloud.githubusercontent.com/assets/10386798/7800782/a9353b96-02cf-11e5-89a5-443f89b7d0d0.png)

**Comment by muteor** [comment]
This has been fixed, it should be released in the next day or so.
