### ISSUE TITLE
Oauth2 authorize broken?

### ISSUE THREAD

**Issue by AngeloG** [DeviantArt/DeviantArt-API#54]
There seems to be a bug with the API. I was told to mail it at first, but then told to make a report on Github.

1. Visit this URL in a browser where you are not logged in yet:
https://www.deviantart.com/oauth2/authorize?response_type=code&client_id=2789&redirect_uri=about:blank
2. You'll be prompted to register, or Log In.
3. Click Log In, and enter some valid info.
4. Press the Log In button, and get presented with an error (most easily
seen in IExplore, but also happens on Project Spartan and even Google
Chrome)

See attached screenshot for attempting to log in. According to my logs,
it is being redirected to "https://www.deviantart.com/join/oauth2login"
without any parameters, causing it to die.

![](https://i.imgur.com/FoLYJW4.png)

**Comment by muteor** [comment]
This appears to be working for me, do you have anymore details? Any javascript errors etc in console?

The `https://www.deviantart.com/join/oauth2login` url is a POST action of the form, this just submits the details and then redirects back to your client.

Also I see you are using `about:blank` as the `redirect_uri`, that wont work because you need to be able to access the code returned by the redirect.

**Comment by AngeloG** [comment]
I haven't tested it for a while, when I get home I'll do some more research. (Maybe it was fixed in the meantime, I'm not sure.)

If I remember correctly, I was somehow able to get an `about:blank?access_code` or something similar, which is fine for my program. Or maybe there is some other URL that would be better to redirect to for desktop-based applications?

**Comment by KarsonKimbrel** [comment]
I have not had any reported issues with my apps.

**Comment by muteor** [comment]
Closing, works for me.

**Comment by AngeloG** [comment]
I can still reproduce this on Internet Explorer 11. The problem could indeed be caused by the use of `about:blank`, but then there should be a substitute callback URL for apps that are not web-based.

**Comment by muteor** [comment]
Generally with Desktop/Mobile apps you use a custom URI thats registered to the app, like `ms-app://{package-security-identifier}` (http://stackoverflow.com/a/28683645) or if the platform doesn't support that you can start a server on a local port and handle it there. I do this for Node commandline tools that use our api, start a server on localhost:8888 and then get the code from there.
