### ISSUE TITLE
Home feed recieve only new

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#55]
Hi, is there a way to get only new events for home feed, like new deviations, polls and other messages, like the site does? For example, when I see and dismiss these notifications, I'd certainly prefer to get only the newest after that. Is it possible to do this with api? As I can only see that /home feed always get all the history and there's no way to distinguish dismissed ones and new. Thanks.

**Comment by muteor** [comment]
Sadly not, we have the same problems with our apps in that its impossible to accurately provide the user with read/unread functionality. Our apps currently just store what you have viewed and use that to try and figure out the read states.

We are working towards a new system that will fix this, which when released I imagine it will be a totally new set of api endpoints. No eta on this as yet, we have a lot of work to do with upgrading the message centre first.
