### ISSUE TITLE
Create new folder

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#56]
Is there a way to create new folder for favorites/gallery? Or for now we can only use available?

**Comment by muteor** [comment]
I haven't seen any plans to add this just yet, I would hope we will add it soon maybe a few iterations away. Will leave this open so you know when its available.

**Comment by Viachaslau-Zinkevich** [comment]
Thanks! It's not to be really important, just good to know about the possibilities.

**Comment by muteor** [comment]
Have released endpoints for managing folders.

https://www.deviantart.com/developers/http/v1/20160316/collections_folders_create/9a59f4dd4c54b0bd5b93a065a6abb5ed
https://www.deviantart.com/developers/http/v1/20160316/gallery_folders_create/d99d15add0264a91eeab05bd61f4624c

**Comment by Viachaslau-Zinkevich** [comment]
Thanks! Any plans to add ability "renaming" folders?
