### ISSUE TITLE
is_watching user field bug

### ISSUE THREAD

**Issue by KarsonKimbrel** [DeviantArt/DeviantArt-API#57]
I noticed this in the API change log: "Added is_watching field to user object available via expand parameter"
So I went to see what endpoints this affects.  I was unable to find any endpoint where is_watching is not included by default, or any endpoint that has a new expandable user object of some new type.  

Upon further investigation, I did calls using /user/watchers/pickley and /user/friends/pickley , both endpoints included the is_watching field as false.  This is incorrect as pickley and I are dA friends and mutually watch each other.

From my user data from GET https://www.deviantart.com/api/v1/oauth2/user/watchers/pickley?limit=50&expand=user.profile%2Cuser.details%2Cuser.geo%2Cuser.stats
"watch": {
    "friend": true,
    "deviations": true,
     "journals": true,
     "forum_threads": true,
     "critiques": true,
     "scraps": true,
     "activity": true,
     "collections": true
}

From Pickley's user data from GET https://www.deviantart.com/api/v1/oauth2/user/watchers/baronbeandip?limit=50&offset=50&expand=user.profile%2Cuser.details%2Cuser.geo%2Cuser.stats
"watch": {
       "friend": true,
       "deviations": true,
       "journals": true,
       "forum_threads": true,
       "critiques": true,
       "scraps": false,
       "activity": true,
       "collections": true
}

**Comment by galymzhan** [comment]
Browse endpoints (newest, popular, etc) now support expand parameter `?expand=user.watch`, that's what the changelog is about. The watchers and friends sound like a real bug, we'll look into that

**Comment by KarsonKimbrel** [comment]
Thanks!

**Comment by KarsonKimbrel** [comment]
I just tested with /browse/popular and it seems to be returning the correct value for is_watching.

**Comment by muteor** [comment]
Bug should be fixed now.

**Comment by KarsonKimbrel** [comment]
Thanks as usual.
