### ISSUE TITLE
Refresh token 400 Bad Request

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#58]
Hi, once the token expires I get 401 Unauthorized with necessity to refresh token, and generally it works.
But waiting for a night not using the app I then tried to use the token, received 401 to refresh it, tried to refresh and..got 400 Bad Request with {"error":"invalid_request","error_description":"The refresh_token is invalid.","status":"error"}. What is the reason? Is there a way to refresh the token with this, I really don't want to make user authenticate again...
Thanks

**Comment by muteor** [comment]
Sadly once you get the 400 for the refresh token you will need to make the user auth again. Refresh tokens are single-use so any failure will delete the refresh token, so if you hit any sort of network problem or the server fails to send the response the token is already dead. Obviously this isnt great but we designed the system to be strict with this as a refresh token grants access to a users account and we would rather the user have to re-auth than have their token stolen.

One thing we found to watch for was multiple processes trying to refresh the token in parallel, this can cause race conditions that cause refresh errors.
