### ISSUE TITLE
/feed/home comments

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#59]
Hi, I would like to know when and which event type with the /feed/home item can contain comment items?
Thanks

**Comment by KarsonKimbrel** [comment]
I do not see any that use it.  Although it looks like 'status' was designed to return comments (as it shows the number of comments), this may be a bug, lets wait for dA to confirm.

**Comment by muteor** [comment]
Home feeds wont include any comments, its deviations, journals, statuses, collections updates.
