### ISSUE TITLE
/curated/tags 500 Interal server error

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#61]
Hi, I quite often receive errors of this type when trying to get curated tags. The reason: {"error":"server_error","error_description":"There was an error performing your request. Please try again later.","status":"error"}
After that if I retry it goes well, but it happens quiet often. Would you be so kind to investigate?

**Comment by muteor** [comment]
I think this should be sorted now, we were having issues with the tags servers for a little while.
