### ISSUE TITLE
User authentication "code" param missing

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#62]
I found that some of the users sometimes when logging in the application through OAuth 2.0 and getting successful authentication result don't receive "code" param in resulting url. Would you be so kind to check or may be explain when this may happen and how to avoid it?
Thanks

**Comment by galymzhan** [comment]
Do you mean that the user is redirected from authorization page, but the code isn't there? Can you reproduce it or it happens randomly? Might be worth re-checking your redirect url whitelist.

**Comment by Viachaslau-Zinkevich** [comment]
Exactly. The user redirected back to application, but the code isn't there. Unfortunately I didn't manage to reproduce this myself, I get this kind of errors through crash reports service occasionally. As the app is the same and mostly work I think it's not something with the whitelist.

**Comment by Viachaslau-Zinkevich** [comment]
I've also got the following message when returning from authorization:
error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request
The callback URL is specified in white list and is correct.

**Comment by galymzhan** [comment]
That actually explains everything. It means user clicked "Deny" on the authorization page. You can handle it by showing an appropriate message in the app

**Comment by Viachaslau-Zinkevich** [comment]
Thanks! Hopes this is the only problem. I'll close for now, unless I get error without message.
