### ISSUE TITLE
JSONP / Cross-site scripting is missing

### ISSUE THREAD

**Issue by pbakaus** [DeviantArt/DeviantArt-API#63]
Heya,

Just started building JavaScript based app using the Implicit OAuth flow and authenticating works fine, but now I'm stuck, as neither JSONP or CORS seems to be available to make requests.

Option A: Support "format=jsonp", i.e. when passing in a callback, it should return with "callback(orig response)".

Option B: Support CORS: http://enable-cors.org/index.html

Otherwise there seems to be no way to do requests from JS right now, which is a pity!

Thanks much,
Paul

**Comment by muteor** [comment]
CORS is sent when the client is set to implicit in the client settings.

**Comment by pbakaus** [comment]
mhh, thanks for the advice but I can confirm it's not working. My client is set to Implicit, yet CORS isn't working. Anything else I need to configure? Does it have something to do with the original_url thing?

**Comment by muteor** [comment]
We have multiple clients already using this and they are working, I checked your client and it is set correctly.

If you are still having issues please send a request/response log showing the headers sent back from the server.
