### ISSUE TITLE
API call to remove items from Watch feed

### ISSUE THREAD

**Issue by pbakaus** [DeviantArt/DeviantArt-API#64]
I'm building an app to process the watch feed much quicker on mobile devices and the only remaining missing piece is an API to remove something from the Watch feed, i.e.:

/feed/item/delete
(params: user_id, item_id)

or something similar.

**Comment by muteor** [comment]
We wont be adding this, the idea of the feeds is that they are static.

**Comment by pbakaus** [comment]
I fail to understand how they're static, when on DeviantArt itself, they're not? Or are you referring to the API just seeing them as static?

Either way, that's very disappointing. I had a nice little app that I would have loved to share.

**Comment by muteor** [comment]
They are static like a twitter feed in that you cant delete things from it. I know it seems strange if you are used to using message centre on da, but the feeds are a totally different system.

**Comment by pbakaus** [comment]
ok thanks for your clarification! Well I still cling to the hope of getting a message center API at one point then :)
