### ISSUE TITLE
Documentation for bucketid

### ISSUE THREAD

**Issue by KarsonKimbrel** [DeviantArt/DeviantArt-API#66]
I do not feel like there is adequate documentation (I do not know what it is for) for the bucketid field or it's endpoint counterpart: /feed/home/{bucketid}.

**Comment by galymzhan** [comment]
They were released recently along with the separation of Group deviations in Notifications. bucketids are used to get all deviations delivered in a single notification event. Currently they're used for group submissions. We updated the docs and changes will be deployed soon

**Comment by KarsonKimbrel** [comment]
Thanks a lot.
