### ISSUE TITLE
Comment replies via API

### ISSUE THREAD

**Issue by AOmelaienko** [DeviantArt/DeviantArt-API#68]
Is there a way to reply to comments and to get comment hierarchically via DeviantArt API? [API documentation](https://www.deviantart.com/developers/http/v1/20150416) isn't completely clear on that matter.

**Comment by muteor** [comment]
To reply to a comment, you post and just include the commentid of the comment you are replying to:

http://www.deviantart.com/developers/console/comments/comments_post_profile/3ba35af99adb5592f2528e98b88d35bb?url%3Ausername=muteor&id%7Ccomment%7C__mapped%7Ccommentid=9041C47E-CED5-2896-CE0B-45C1EC5AD056&body=I+am+a+reply&da_version=&endpoint=%2Fcomments%2Fpost%2Fprofile%2F%7Busername%7D

You have a couple of options with handling the comment thread, by default it fetches the top level comments but you can also request replies to be included.

So top level thread:

http://www.deviantart.com/developers/console/comments/comments_profile/ea966c38b14c96158b95b17f4ae9f493?url%3Ausername=muteor&id%7Ccomment%7C__mapped%7Ccommentid=&maxdepth=&offset=&limit=&da_version=&grant_type=authorization_code&endpoint=%2Fcomments%2Fprofile%2F%7Busername%7D

Thread with replies (maxdepth):

http://www.deviantart.com/developers/console/comments/comments_profile/ea966c38b14c96158b95b17f4ae9f493?url%3Ausername=muteor&id%7Ccomment%7C__mapped%7Ccommentid=&maxdepth=5&offset=&limit=&da_version=&grant_type=authorization_code&endpoint=%2Fcomments%2Fprofile%2F%7Busername%7D

And fetching children of a particular comment:

http://www.deviantart.com/developers/console/comments/comments_profile/ea966c38b14c96158b95b17f4ae9f493?url%3Ausername=muteor&id%7Ccomment%7C__mapped%7Ccommentid=9675D5BE-1AD1-971F-2554-845C31B839B8&maxdepth=&offset=&limit=&da_version=&grant_type=authorization_code&endpoint=%2Fcomments%2Fprofile%2F%7Busername%7D

We also have an endpoint for fetching siblings, for when you have a comment and need to find it within its thread context:

http://www.deviantart.com/developers/console/comments/comments_siblings/c5bc1b565662bdb59d86b2c326f5281f?id%7Ccomment%7C__mapped%7Curl%3Acommentid=3A15BDDA-979B-7EB8-26A7-6C963812388C&ext_item=true&offset=&limit=&da_version=&grant_type=authorization_code&rconly=false&daml=false&endpoint=%2Fcomments%2F%7Bcommentid%7D%2Fsiblings

Hope that helps.
