### ISSUE TITLE
Suggestion: create batch options for submissions

### ISSUE THREAD

**Issue by bamachine** [DeviantArt/DeviantArt-API#69]
We need to create an option that would allow members to edit multiple submissions at one time. Just something where we can apply all the features in the normal submission process to more than one piece, either  a batch process that would apply the same change to all selected pieces. Or maybe something that would let us edit a selection of pieces and move back and forth between them smoothly like you would find in a photo editing program.  For the second option I recommend an interface similar to zoom browser ex where you can select a folder and all the art appears in a scrolling screen in thumbnails at the bottom.   I'm sure many deviants would appreciate this.

**Comment by muteor** [comment]
Think you have the wrong place, you want the suggestions forum https://support.deviantart.com/forums/21059041-DeviantArt-Suggestions
