### ISSUE TITLE
RSS no longer working on server

### ISSUE THREAD

**Issue by iangilman** [DeviantArt/DeviantArt-API#70]
My PHP app has been using the RSS feed as specified here: 

https://www.deviantart.com/developers/rss

...but lately it's been getting these errors: 

PHP Warning:  file_get_contents(http://backend.deviantart.com/rss.xml): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden 

The same RSS URL works fine when I hit it in the browser. 

How do I access that feed now?

**Comment by muteor** [comment]
This should be fixed now.

**Comment by iangilman** [comment]
Still broken. Has the fix been deployed?

**Comment by muteor** [comment]
Missed you were using `file_get_contents()` this wont work because you need to send a user agent and request compressed content.

You can do this using a stream:

```
$opts = [
    'http' => [
        'method' => 'GET',
        'header' => implode("\n", ['Accept-Encoding: gzip,deflate', 'User-Agent: MyUserAgent']),
    ]
];
$context = stream_context_create($opts);
$content = file_get_contents('http://backend.deviantart.com/rss.xml', false, $context);

var_dump(gzinflate(substr($content,10)));
```

Though curl is better because it handles the de-compression automatically for you:

```
$ch = curl_init('http://backend.deviantart.com/rss.xml');
curl_setopt($ch, CURLOPT_ENCODING , ''); // request compressed
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_USERAGENT, 'MyUserAgent');
$output = curl_exec($ch);
curl_close($ch);
var_dump($output);
```

**Comment by iangilman** [comment]
Awesome, that did it! Thank you so much for your help!

**Comment by scadl** [comment]
I fixed my code with 1st method, and it working again! 
Thank you, <b>muteor</b>!
