### ISSUE TITLE
oAuth & oEmbed endpoints return 403 Forbidden since maintenance

### ISSUE THREAD

**Issue by DJDavid98** [DeviantArt/DeviantArt-API#71]
After the maintenance yesterday, all API endpoints on my server are bouncing back with the HTTP code 403. I'm not sure if my app and/or server got hit by a rate limit or not, but the oEmbed API works just fine when I open them in my browser, but authenticated API requests fail regardless of which server I'm sending them from, local or production. #70 is likely related to this as well.

Last time I had this issue, it was related to the `User-Agent` header field being left empty, but after setting it, the requests started working. Now, changing the header to my own browser's didn't allow my request to pass, still 403.

For the oEmbded API, the requests only fail if the `Accept-Encoding` header is not set, at which point a server other than Apache (`ECD (cpm/F830)`) tries to serve the request, and that's what sends the 403.

**Comment by KarsonKimbrel** [comment]
I was also having issues when calling /token, although it seems to be working for me now.  
I was not able to retrieve the response code when it was not working for me as when I enabled my logging mode it started working.  
DeathShadow--666 says it is still not working for him though.

**Comment by DeathShadow** [comment]
I get:
```
string(459) "HTTP/1.1 503 Service Unavailable
Date: Tue, 28 Jul 2015 20:02:04 GMT
Server: Apache
Cache-Control: Private, no-cache, no-store, must-revalidate, max-age=0, max-stale=0, post-check=0, pre-check=0
Pragma: no-cache
Expires: 0
Vary: Accept-Encoding
Content-Length: 118
Connection: close
Content-Type: application/json; charset=utf-8

{"error":"server_error","error_description":"The service is currently unavailable, please try later","status":"error"}"
```

when i use php's fsockopen() function, but when i use php's curl, curl from command line, or browser, it works fine.

**Comment by DJDavid98** [comment]
I'm using cURL and that's where I'm having the errors come up.

**Comment by DeathShadow** [comment]
after getting some rest, i decided to tickle the problem i got again... and it seems i solved my problem.

for some reason, using <code>fsockopen('ssl://deviantart.com', 443, $errno, $errstr, 30);</code> gives the 503, but using <code>fsockopen('ssl://www.deviantart.com', 443, $errno, $errstr, 30);</code> doesn't and works fine. Can someone from deviantART look into this?

**Comment by muteor** [comment]
The 503 and 403 errors should be fixed now. We are still finishing quite a large server migration so please bear with us while we iron out issues.

**Comment by DJDavid98** [comment]
I'm still getting 403 errors when trying to authenticate

**Comment by muteor** [comment]
Are you sending Accept-Encoding and User agent?

**Comment by DJDavid98** [comment]
It appears that my PHP configuration's default user agent setting didn't get added to cURL requests. The issue is now resolved.
