### ISSUE TITLE
Deviation Comment hidden field unexpected empty string

### ISSUE THREAD

**Issue by KarsonKimbrel** [DeviantArt/DeviantArt-API#72]
When making a call to https://www.deviantart.com/api/v1/oauth2/comments/deviation/48EB2341-8862-4D88-C38D-5567AAD334BA one of the comment objects returned has a hidden field set to empty string instead of null or one of the documented reasons as expected.

**Comment by muteor** [comment]
Hmm this is working for me I get null rather than empty string.
```
{
            "commentid": "DA54C298-BB10-9BC9-AEE1-BE487B4E11F9",
            "parentid": null,
            "posted": "2015-05-31T21:07:50-0700",
            "replies": 3,
            "hidden": null,
            "body": "...
```

**Comment by KarsonKimbrel** [comment]
I tried the call again and it seems to be ok now.  I'll just chalk it up to yesterday's issues.
