### ISSUE TITLE
Authorization scope not respected?

### ISSUE THREAD

**Issue by kyl191** [DeviantArt/DeviantArt-API#73]
Background: I'm trying to upgrade to the latest API version from the unversioned API. 

I'm trying to use the /stash/item/{itemid} and the /stash/{stashid} endpoints to retrieve metadata, but the endpoints are returning a 403 error with insufficient_scope, and the description "The requested resource requires a higher scope than the user has allowed the client to access, client needs to re-authorize."

However, I'm still able to upload images, which apparently also needs the 'stash' scope, so I'm confused as to what scopes I'm missing.

I've deauthorized & reauthorized my app (which should have fixed the scope issue), but I'm still seeing the above behaviour.

**Comment by galymzhan** [comment]
Can you double check you're using correct client id and access token? 
Also, full error response should have a list of missing scopes, although these endpoints only require "stash"
