### ISSUE TITLE
Another 'scope' and err403 issue..

### ISSUE THREAD

**Issue by scadl** [DeviantArt/DeviantArt-API#74]
Recently I wrote PHP app, which should read my feed, using dA API, than parse it, and write links of new artworks from feed into thirdparty database. I tested it 2 weeks ago, and everything works fine.

I'm used "The Authorization Code Grant" to get token for reading feed. Now, about 1,5 week I can't use my app, because it constantly receiving 403 error (not documented in API help), during getting access token step, no matter, how many hours I'm waiting between attempts.

Also I tried to implement "The Implicit Grant", which is actually answers with access token, but when I asking feed with this token, I'm again getting this 403 error! I'm using file_get_contents function to read json feed, but I also tried curl, and didn't revived any error details. Also I tried too use header with dA-minor-version, but still reciving this error.

Strange, but if I just open link, called by my script in new browser tab, it works. I tried to pause my script, but it didn't helping. What else could cause 403 error, when requesting by a script?

Please help me to find out, whats wrong. I can't use developer console for this, cause it's not an error in request. 

My APP client_id: 3286

**Comment by muteor** [comment]
You need to send useragent and request encoding, see my comment here for an example: https://github.com/DeviantArt/DeviantArt-API/issues/70#issuecomment-126042639
