### ISSUE TITLE
Suggestion: Add an option to restrict scope of API in application settings.

### ISSUE THREAD

**Issue by OrrinFox** [DeviantArt/DeviantArt-API#75]
In open source applications that use oAuth, such as a dAmn chat bot or client, the scope could be changed by the end user and could be abused.  If an option to restrict the scope is added to the application settings and enforced, it could prevent this. I talked with a couple others about the subject and got mixed reviews, but I thought I would bring it up here.

**Comment by muteor** [comment]
I am not sure I see the chance for abuse here, if a user wants to to change their scopes they can. The idea of a scope is that its a permission given by the user to the application. So they have to approve the scope access anyway so should always be aware of what access the app has to their account. If you have a more specific example of a way to abuse the scope please let me know.
