### ISSUE TITLE
Curated data repeats one article many times

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#76]
Hi, there's an issue lately, that exactly one article is repeated for many time in a row. Some users think this is a app bug, but it's API that returns this data. To reproduce, just retrieve sequentially /curated articles and watch the appearance of deviation with id: 6D7AEC6B-A1C6-2DBC-ED06-1318D6A855F1

**Comment by muteor** [comment]
Curated is curated so it was probably human error.
