### ISSUE TITLE
Inability to login

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#77]
Hi. 
I often receive negative feedback from users due to their inability to login through standard OAuth 2.0 process because of DA provided pages.
The problem almost each time is that users click "Accept" button on the last page (when you need to allow the app to access data) and nothing happens. No reaction at all, no kind of notification, message box or anything. Some of users simply forget to tick the checkbox and I always have to remind each and every of them. But in some cases even after selected checkbox, nothing happens.
One of users informed me, that there was some applications blocked by him on the site and that didn't allow him to login in my app. Only removing them from black list allowed.
So the question is if it's possible to somehow enhance the login pages with more additional information regarding inabilities to press "Accept" button? May be some information on WHY the can't, so that users now to check the checkbox, or remove apps from blacklist.
As for now, the worst reviews I personally get from people, who can't login due to Accept button. Would be nice to improve usability.
Thanks.

**Comment by muteor** [comment]
I have made the checkbox bigger and bolded the text so its a little more obvious that they need to check the box. I also duplicated the error to the top so they see it without scrolling. See if that helps :)
