### ISSUE TITLE
Invalid SSL certificate on t15.deviantart.net, image refuses to load over HTTPS

### ISSUE THREAD

**Issue by DJDavid98** [DeviantArt/DeviantArt-API#78]
A request to the API returned [the following image](http://t15.deviantart.net/1g0zo8lWm2h0PhJOg4yUMvd57zk=/fit-in/300x900/filters:no_upscale():origin()/pre08/1f61/th/pre/i/2015/262/3/2/rarity_loves_the_delivery_pony_by_dcencia-d9a5noh.png), and my website uses a simple replace operation to change HTTP URLs into HTTPS, which results in [the new URL](https://t15.deviantart.net/1g0zo8lWm2h0PhJOg4yUMvd57zk=/fit-in/300x900/filters:no_upscale():origin()/pre08/1f61/th/pre/i/2015/262/3/2/rarity_loves_the_delivery_pony_by_dcencia-d9a5noh.png) not serving the image due to a certificate error. I haven't had this happen before, it appears to be specific to this domain.

![Your connection is not private Attackers might be trying to steal your information from t15.deviantart.net (for example, passwords, messages or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID](https://cloud.githubusercontent.com/assets/3200580/9982606/7b462130-5fe2-11e5-90ef-50cfc0e1b07a.png)

**Comment by galymzhan** [comment]
We are doing some changes in SSL setup, try again sometime soon
