### ISSUE TITLE
Inability to login

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#79]
Hi, I've noticed really strange behavior that wasn't present earlier. I wonder, if the OAuth authorization page was somehow edited/modified from previous versions.
The problem that WP 8.1 (IE 11 mobile) users reported actually present but really randomly. I managed to see it on emulator. These are the cases:
1) After you enter valid login and password, for some reason browser returns UserCancel code, with errorCode = 0 and empty string as description. The same behavior (when it's valid) when user actually decides not to login and returns manually. But this looks like the server sends such a response. I managed to fix it manually for my user when login in  web version and closed all "other sessions" in settings.
2) If user enters valid credentials and gets to the page with authorization,selects checkbox and presses Authorize -- simply nothing happens. Like it wasn't pressed. The same is for Deny button. No request/response, nothing.
3) After the request for token revocation is sent -- the session in Settings of web-version is still alive and needs to get closed forcefully from settings.
I do really hope this can be helped. Thanks!

**Comment by muteor** [comment]
> 1) After you enter valid login and password, for some reason browser returns UserCancel code, with errorCode = 0 and empty string as  description. The same behavior (when it's valid) when user actually decides not to login and returns  manually. But this looks like the server sends such a response. I managed to fix it manually for my user  when login in web version and closed all "other sessions" in settings.

Do you have an example of the response you get, would be useful for tracking down that case.

> 2) If user enters valid credentials and gets to the page with authorization,selects checkbox and presses Authorize -- simply nothing happens. Like it wasn't pressed. The same is for Deny button. No request/response, nothing.

Sounds like IE sucks :) Do you have any errors in the console? When this happens it could be some sort of javascript error which should show up in console.

> 3) After the request for token revocation is sent -- the session in Settings of web-version is still alive and needs to get closed forcefully from settings.

Depends which sessions you are talking about, OAuth sessions are not related to web sessions. The only thing in settings that relates to OAuth is the app authorizations.

**Comment by Viachaslau-Zinkevich** [comment]
1) Unfortunately no, I can't get them from the emulator( I understand it's quite hard to check this and fix, if there is even a problem
2) Of course IE sucks, who would argue. The problem is that it actually worked. I managed to get some logs from JS, hope this helps (at the end of the message).
3) OAuth session may be not connected, but as soon as I try to login through OAuth I get a session in the list of other sessions in Settings with browser/device set to Windows Mobile.

Logs:
'IExplore.exe' (Script): Loaded 'Script Code ((null))'. 
Exception was thrown at line 16, column 1357 in https://www.google-analytics.com/analytics.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 16, column 1460 in https://www.google-analytics.com/analytics.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 16, column 1610 in https://www.google-analytics.com/analytics.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 8, column 151 in https://www.google-analytics.com/analytics.js
0x800a138f - JavaScript runtime error: Unable to get property 'getRandomValues' of undefined or null reference
Exception was thrown at line 8, column 24118 in https://st.deviantart.net/css/deviantart-network_jc.js?3758961921
0x800a139e - JavaScript runtime error: SyntaxError
Exception was thrown at line 8, column 24343 in https://st.deviantart.net/css/deviantart-network_jc.js?3758961921
0x800a139e - JavaScript runtime error: SyntaxError
Exception was thrown at line 42, column 400 in https://partner.googleadservices.com/gpt/pubads_impl_73.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 42, column 514 in https://partner.googleadservices.com/gpt/pubads_impl_73.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 43, column 86 in https://partner.googleadservices.com/gpt/pubads_impl_73.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 8, column 521 in https://partner.googleadservices.com/gpt/pubads_impl_73.js
0x800a138f - JavaScript runtime error: Unable to get property 'getRandomValues' of undefined or null reference
Exception was thrown at line 14, column 363 in https://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 14, column 470 in https://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 15, column 20 in https://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 15, column 199 in https://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html
0x800a139e - JavaScript runtime error: Cannot parse serialized data to extract content
Exception was thrown at line 8, column 151 in https://www.google-analytics.com/analytics.js
0x800a138f - JavaScript runtime error: Unable to get property 'getRandomValues' of undefined or null reference
Exception was thrown at line 8, column 151 in https://www.google-analytics.com/analytics.js
0x800a138f - JavaScript runtime error: Unable to get property 'getRandomValues' of undefined or null reference
Exception was thrown at line 16, column 1357 in https://www.google-analytics.com/analytics.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 16, column 1460 in https://www.google-analytics.com/analytics.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 16, column 1610 in https://www.google-analytics.com/analytics.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 8, column 151 in https://www.google-analytics.com/analytics.js
0x800a138f - JavaScript runtime error: Unable to get property 'getRandomValues' of undefined or null reference
Exception was thrown at line 8, column 24118 in https://st.deviantart.net/css/deviantart-network_jc.js?3758961921
0x800a139e - JavaScript runtime error: SyntaxError
Exception was thrown at line 8, column 24343 in https://st.deviantart.net/css/deviantart-network_jc.js?3758961921
0x800a139e - JavaScript runtime error: SyntaxError
Exception was thrown at line 42, column 400 in https://partner.googleadservices.com/gpt/pubads_impl_73.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 42, column 514 in https://partner.googleadservices.com/gpt/pubads_impl_73.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 43, column 86 in https://partner.googleadservices.com/gpt/pubads_impl_73.js
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 8, column 521 in https://partner.googleadservices.com/gpt/pubads_impl_73.js
0x800a138f - JavaScript runtime error: Unable to get property 'getRandomValues' of undefined or null reference
Exception was thrown at line 8, column 521 in https://partner.googleadservices.com/gpt/pubads_impl_73.js
0x800a138f - JavaScript runtime error: Unable to get property 'getRandomValues' of undefined or null reference
Exception was thrown at line 14, column 363 in https://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 14, column 470 in https://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 15, column 20 in https://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html
0x800a01ad - JavaScript runtime error: Automation server can't create object
Exception was thrown at line 15, column 199 in https://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html
0x800a139e - JavaScript runtime error: Cannot parse serialized data to extract content
Exception was thrown at line 8, column 16285 in https://st.deviantart.net/css/deviantart-network_jc.js?3758961921
0x800a139e - JavaScript runtime error: SyntaxError

**Comment by Viachaslau-Zinkevich** [comment]
@muteor small update: the problem still happens but it seams that actually cleaning and forcefully closing all of the sessions and if possible remove app from authorized helps then to login. So it should be some connection with sessions, otherwise how can this help?

**Comment by muteor** [comment]
I had a few people test this for me and no-one was able to reproduce the error on IE11. I still think its probably some strange edge case in IE but not sure what.

**Comment by Viachaslau-Zinkevich** [comment]
@muteor I personally never saw it in my Wp8.1 Lumia, only in emulator, but user's reviews actually report the problem exists and the advice with sessions helps, which is strange.
The problem is, that it reproduces in WebAuthenticationBroker, which is not the Browser, but creates it's one system WebView, which is hard to test.

**Comment by muteor** [comment]
Closing as we could never reproduce.
