### ISSUE TITLE
Message types docs

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#80]
Hi, 
is there any full list of message types that one can receive? Like "feedback.watch" and others;
And would be very nice to have docs concerning what type of message which fields provide, as for now it's not quite obvious what will be provided in different cases.
Thanks

**Comment by Viachaslau-Zinkevich** [comment]
And what about folderId para? Which kind of folders are meant here and where to get this id from?

**Comment by muteor** [comment]
Here is the list:

```
'feedback.watch',
'feedback.favourite',
'feedback.collect',
'feedback.collection_favourite',
'feedback.collection_collect',
'feedback.gallery_favourite',
'feedback.gallery_collect',
'feedback.print_sold',
'feedback.print_accepted',
'feedback.deviation_sold_for_points',
'feedback.deviation_bought_for_points',
'feedback.print_accepted',
'feedback.download_available',
'feedback.download_updated',
'feedback.group_joined',
'feedback.group_changed_role',
'feedback.group_left',
'feedback.group_removed_deviation',
'feedback.badge_given',
'feedback.badge_levelled',
'feedback.badge_accessory',
'feedback.birthday',
'feedback.da_birthday',
'feedback.dd_to_author',
'feedback.dd_to_suggester',
'feedback.comment',
'feedback.reply',
```

We will update the docs at some point to document these, however at this point the messages endpoints should be considered beta and subject to change. We will hopefully be re-architecting the message system in the future so are holding off sinking too much time into fully documenting things at this time.

The `folderid` field is actually there by mistake, we will remove it.

**Comment by Viachaslau-Zinkevich** [comment]
@muteor thanks a lot! Would you be so kind to specify which of them are actually in use for now, please?
