### ISSUE TITLE
Suggestion: Move information in API documentation

### ISSUE THREAD

**Issue by vinyldarkscratch** [DeviantArt/DeviantArt-API#84]
I believe that the text of "All APIs require that your client sends a User Agent and uses HTTP compression. Clients making requests not doing this will be rejected." is misplaced, and not noticeable.  I have spent up to eight hours work time trying to figure out why my code wouldn't connect, and I didn't notice the small 11pt italics on the intro page.  I think it should be at the top of authentication, in bold and large text.

**Comment by muteor** [comment]
Have added a new section to the errors documentation, hopefully its easier to find now.
