### ISSUE TITLE
Inconsistent handling of hashes in return URL

### ISSUE THREAD

**Issue by Provinite** [DeviantArt/DeviantArt-API#85]
While testing, I noticed some inconsistent behavior involving hashes in return urls.

**Case 1**
- User is already logged into DeviantArt
- User is sent to authorization url with return url = `http://mysite.com/login/return#main`

**Outcome**
- User is sent back to http://mysite.com/login/return#main

--------------------------

**Case 2**
- User is *not* logged into DeviantArt
- User is sent to authorization url with return url = `http://mysite.com/login/return#main`

**Outcome**
- User is sent back to http://mysite.com/login/return

In the second case the hash is discarded. Is this intended behavior, or should there be some escaping that happens/other option?

There are certainly workarounds, I'd just like to know if this is intended behavior, a bug, or simply a misuse of the system on my end.

Thanks for your time.

**Comment by muteor** [comment]
We dont support url fragments in the redirect_uri, you should actually get an error if you try. For me I get a redirect error screen when trying to use a hash. Could you provide some more information about how you are passing that?

**Comment by Provinite** [comment]
Sure thing. The user is redirected via javascript `window.location.href` to a link generated via PhP like so:

    apiAuthBaseUrl .
     'authorize?response_type=code' .
     '&scope=' . $this->apiScope .
     '&client_id=' . $this->apiClientId .
     '&redirect_uri=' . $this->returnUri .
     '&state=' . $state;

Sample URL:

     https://www.deviantart.com/oauth2/authorize?response_type=code&scope=user browse&client_id=MY_API_CLIENT_ID&redirect_url=http://www.mysite.com/login/apireturn#main2&state=SomeRandomlyGeneratedStateValue

**Comment by muteor** [comment]
Ok thanks for the report, will do some more tests for this later.
