### ISSUE TITLE
Curated service returns only 4 entries

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#86]
Hi,
there's an issue with /curated for last few days, that the service return only 4 entries and says there's nothing more to show.

**Comment by muteor** [comment]
We are no longer curating content, hence the lack of content. This also reminds me that we need to end of life these endpoints, we have removed the Today page from our apps already. Sorry for not being able to give much prior notice on this.

**Comment by Viachaslau-Zinkevich** [comment]
@muteor oh, I see, no problem, thanks for letting me know!

**Comment by Viachaslau-Zinkevich** [comment]
@muteor but if I may ask you, just need to know about availability of such complex content as curated data. It was always quite a large and complex html page to show. I'd like to know is it possible for anyone to create the same things? Just to know if I still need the ability to show html page or this(curated) was the only way(source) of such pages?

**Comment by muteor** [comment]
Yeah these can be created by users via journal skins, like this: http://muteor.deviantart.com/journal/Updated-Sta-sh-API-526658081
