### ISSUE TITLE
issue with scope setting while authorization

### ISSUE THREAD

**Issue by EisenerGustav** [DeviantArt/DeviantArt-API#87]
Hello,

I've faced with an issue while authorization in DeviantArt Api. I 'm trying to specify the scope (feed or user.manage) but I receive only such response : 
{"access_token":"some_token","token_type":"Bearer","expires_in":3600,"refresh_token":"some_another_token","scope":"basic","status":"success"}
So API gives me only basic scope but I need user.manage. What have I done wrong? or is it API issue?

thank you,
Artem

**Comment by EisenerGustav** [comment]
I've requested the scope the way you've described. and result is the same:
{"access_token":"423255cc4e7441f87ff254ca68e573099b068bb9e5c8e36df2","token_type":"Bearer","expires_in":3600,"refresh_token":"35a1359e7927f38cd48fab6c7b67a140f047f1ff","scope":"basic","status":"success"}..
so scope is still 'basic'

**Comment by muteor** [comment]
Hmm its working for me:

```
API (live)> authorize
Starting authorization process
Request Auth https://www.deviantart.com/oauth2/authorize?response_type=code&client_id=...&scope=user+user.manage&redirect_uri=https://127.0.0.1:8888/
API (live)> Fetching token https://www.deviantart.com/oauth2/token?grant_type=authorization_code&client_id=...&client_secret=...&code=...&redirect_uri=https://127.0.0.1:8888/
{"access_token":"...","token_type":"Bearer","expires_in":3600,"refresh_token":"...","scope":"user user.manage","status":"success"}
Authorized token is  ...
API (live)>
```

Have you tried revoking access and then re-authorising? Could be that for some reason its not picking up the change in scope.

Also you might want to not post your tokens :)

**Comment by EisenerGustav** [comment]
It works now, thank tou. I think we could close this issue
18 лист. 2015 19:13, користувач "Keith Pope" <notifications@github.com>
написав:
