### ISSUE TITLE
Endpoint to get list of group members / check user's group memberships

### ISSUE THREAD

**Issue by DJDavid98** [DeviantArt/DeviantArt-API#88]
It'd be nice to have an API endpoint that would somehow allow me to check if a user is a member of a specific group. The 2 approaches I can think of are:

 1. Get a list of all members for a group, and look through it (more possibilities)
 2. Get a list of groups a user is a member of (less possibilities, but still gets the job done)

Though for my purposes it'd be enough if you could remove the `100` cap on the `limit` GET parameter on `http://<groupname>.deviantart.com/modals/memberlist/?limit=#`, or even better, if, for example a negative number is passed as the limit, don't paginate the list at all.

**Comment by muteor** [comment]
We are currently working on group API's that cover all group functions, no ETA on them just yet though.
