### ISSUE TITLE
redirect_uri does not match 

### ISSUE THREAD

**Issue by issaysa** [DeviantArt/DeviantArt-API#89]
I set the OAuth2 Redirect URI Whitelist like this below. 
http://localhost:3000 https://sample.jp http://sample.jp

When I do this below.
1. Request to https://www.deviantart.com/oauth2/authorize?client_id=****&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fdeviantart%2Fcallback&response_type=code&state=*******************
2. Redirect to http://localhost:3000/auth/deviantart/callback?code=***********&state=******************
3. Post to https://www.deviantart.com/oauth2/token with body 
{"grant_type"=>"authorization_code", "code"=>"****", "client_id"=>"****", "client_secret"=>"*****", "redirect_uri"=>"http://localhost:3000/auth/deviantart/callback?code=*****&state=*****"}
and header 
{"Content-Type"=>"application/x-www-form-urlencoded"}

4. The response is

{"error":"invalid_request","error_description":"redirect_uri does not match authorized redirect_uri.","status":"error"}

I think the redirect_uri is set well because the first redirect to http://localhost:3000/auth/deviantart/callback?code=***********&state=****************** occurs without any problems.

If you have any idea what's wrong, please let me know.
Thanks in advance.

**Comment by issaysa** [comment]
I fixed this.
The reason was the redirect_uri at step-3 shouldn't have had parameters after '?'.

**Comment by joshtwo** [comment]
Yeah, I've gotten tripped up by that before by accident.
