### ISSUE TITLE
Suggestion: Endpoint to provide client with the Submission Policy and ToS

### ISSUE THREAD

**Issue by KarsonKimbrel** [DeviantArt/DeviantArt-API#9]
I would like to suggest an endpoint to provide the client with text and or HTML of the DeviantArt ToS and Submission Policy.

**Comment by KarsonKimbrel** [comment]
It may also be nice to have an endpoint for the privacy policy as well, as seen below.
Examples of similar endpoints like this in use by another company (Twitter): https://dev.twitter.com/rest/reference/get/help/tos and https://dev.twitter.com/rest/reference/get/help/privacy

**Comment by galymzhan** [comment]
We added a couple of new endpoints, please see the changelog
