### ISSUE TITLE
Sta.sh endpoints return stack/item IDs as floating-point numbers, rounding causes loss of actual value

### ISSUE THREAD

**Issue by DJDavid98** [DeviantArt/DeviantArt-API#90]
When I make a request to `https://www.deviantart.com/api/v1/oauth2/stash/delta` I get results similar to this:
```json
{
    "cursor": "…",
    "has_more": true,
    "next_offset": 120,
    "reset": false,
    "entries": [
        {
            "itemid": 6.966443816144e+14,
            "stackid": 3.8323063099599e+15,
            "metadata": {
                "title": "…",
                "description": null,
                "artist_comments": "",
                "original_url": "",
                "category": "",
                "creation_time": 1449842481,
                "files": [ ],
                "stackid": 3.8323063099599e+15,
                "itemid": 6.966443816144e+14,
                "tags": []
            },
            "position": 0
        },
        {
            "itemid": 5.0263339867839e+15,
            "stackid": 7.3504223941299e+15,
            "metadata": {
                "title": "…",
                "description": null,
                "artist_comments": "",
                "original_url": "",
                "category": "",
                "creation_time": 1449307452,
                "files": [ ],
                "stackid": 7.3504223941299e+15,
                "itemid": 5.0263339867839e+15,
                "tags": []
            },
            "position": 0
        }
    ]
}
```

Notice how `itemid` and `stackid` are floats? In most cases, this causes the element to not be found, as the last 2 digits of the ID end up always being `00`. In my case, the ID of the first element in this example is actually `696644381614402` as verified by the Developer API Console's Sta.sh button, but according to this request it's `6.966443816144e+14` which equals to `696644381614400`. The 2 is gone! The second item's actual ID is `7034002736838535` but the returned value here represents `7034002736838500`.

I've verified that this happens even if I place the number as an integer into the locally cached `json` file itself, it's rounded automatically by the parser. I suggest serving these IDs as strings to prevent this from happening.

**Comment by muteor** [comment]
This seems to work for me, dev console gives me:

```
{
            "itemid": 5367869032320101,
            "stackid": 1712346847638488,
            "metadata": {
                "title": "oobe gruser IE",
                "description": null,
                "artist_comments": "",
                "original_url": "",
                "category": "",
                "creation_time": 1364397194,
```

**Comment by DJDavid98** [comment]
When the file is parsed with PHP, the numbers get converted to a float. Try pasting that JSON into a file and then read it with

    var_dump(json_decode(file_get_contents('file.json'), true));

**Comment by galymzhan** [comment]
Can you try this instead:

```
var_dump(json_decode(file_get_contents('file.json'), true, 512, JSON_BIGINT_AS_STRING));
```

**Comment by muteor** [comment]
Ah yeah thats PHP being dumb, they added an option to fix though:

https://3v4l.org/6qCnt
