### ISSUE TITLE
429 error issue

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#91]
Hi, I see a strange behavior with 429 error.
When I login to the app and use user-based token I get the following behavior:
1) After using for some time with and getting 429 the timeout for it is about 30 minutes! I would love to believe it's not an expected behavior.
2) Even though I login on different devices, after I get 429 on one device -- I get it everywhere, until I logout. Then everything loads again. So as far as I can tell, all of the user tokens are blocked for the app. I guess it's not what you meant...
Thanks

**Comment by muteor** [comment]
That can be correct, there are 3 limits you can get client, user or ip. The limit itself is a velocity filter so once triggered you need to leave it enough time to decay back out of the block.

**Comment by Viachaslau-Zinkevich** [comment]
I understand, but it seams a bit strange for me, that user who logged in reaches limit far easier and faster then the one who doesn't. And would you please investigate why does it take so long for user to wait as I actually tested without running an app -- that was 30 minutes. This creates really bad experience, I believe...

**Comment by muteor** [comment]
The user limit is pretty rarely triggered, I see ~20 per hour which seems reasonable from here. 

I can adjust your clients settings, please email me (muteor deviantart.com) with your client_id and some info about the app and I will look into getting your client moved into a different filter bracket.
