### ISSUE TITLE
Do we require an API to show simply our galley images inside android app?

### ISSUE THREAD

**Issue by unitedart** [DeviantArt/DeviantArt-API#92]
I am asking this here because we don't get any response from anywhere else, We have a deviantart gallery with our own images, We are showing it inside an android app through gridview directly using the image url. Is it illegal to do so? can somebody please guide us?

**Comment by muteor** [comment]
As long as you follow our terms its fine:

http://about.deviantart.com/policy/service/
http://about.deviantart.com/policy/copyright/
http://about.deviantart.com/policy/api/
http://about.deviantart.com/policy/etiquette/

**Comment by unitedart** [comment]
Yeah thanks, But can you please let us know what you think personally.
1) we are using our own Works that are uploaded in Deviantart. (their URLs)
2) we are showing it in a gridview like a gallery where people can set it as wallpaper for their devices.
3) we will also add deviantart link so that if they want they can check the gallery in deviantart website too. 
Is this okay according to you? We read all service,copyright,api,etiquette. But we are still not sure.It will be just like sharing a link in facebook website right? Thanks in advance. Sorry if we disturbed
