### ISSUE TITLE
RSS feed issue

### ISSUE THREAD

**Issue by shiyunhe** [DeviantArt/DeviantArt-API#93]
RSS feed used to work properly. But lately, it stops working properly and return the same results for popular and newest feed. The results for all category, all time, and popular feed is not correct.

Newest
http://backend.deviantart.com/rss.xml?type=deviation&q=sort%3Atime&offset=0

Popular
http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular&offset=0

**Comment by redcapital** [comment]
Please check again, it should be fixed now

**Comment by shiyunhe** [comment]
Most of all categories, popular feeds are still seem to be broken. 

The following feeds seem to return the same results:
All time: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular&offset=0
24 hours: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A24h&offset=0
3 days: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A72h&offset=0
1 week: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A168h&offset=0
1 month: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A720h&offset=0

The only exception is 8 hours: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A8h&offset=0
