### ISSUE TITLE
Can't get client access token with Client Credentials

### ISSUE THREAD

**Issue by TwelveParsecs** [DeviantArt/DeviantArt-API#94]
I can get a client access token in terminal but when I try to do it with the same information in php cURL I get a 403 error. Why would this be happening?

**Comment by muteor** [comment]
You need to make sure you are sending a user agent and requesting compressed response, E.g.

```
$ch = curl_init('https://...');
curl_setopt($ch, CURLOPT_ENCODING , ''); // request compressed
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_USERAGENT, 'MyUserAgent');
$output = curl_exec($ch);
curl_close($ch);
```

**Comment by TwelveParsecs** [comment]
Excellent, that did the trick. Thanks!
