### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by shiyunhe** [DeviantArt/DeviantArt-API#95]
Most of all categories, popular feeds seem to be broken.

The following feeds seem to return the same results:
All time: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular&offset=0
24 hours: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A24h&offset=0
3 days: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A72h&offset=0
1 week: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A168h&offset=0
1 month: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A720h&offset=0

The only exception is 8 hours: http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+max_age%3A8h&offset=0

**Comment by redcapital** [comment]
Thanks, fixed. Anything else you noticed?

**Comment by shiyunhe** [comment]
Thanks for your quick response. I will let you know if I find anything else.
