### ISSUE TITLE
/feed/home how get more records than 10

### ISSUE THREAD

**Issue by franckyg** [DeviantArt/DeviantArt-API#96]
Hi,

When I access to /feed/home I can only get the 10 last records even if hasMore is set to true.
I tried to add offset parameter to 10 without success.
Is there something I missed ?

Thanks
Franck

**Comment by muteor** [comment]
feed/home uses cursor based pagination, so you use the cursor from the response to fetch more items:

https://www.deviantart.com/developers/pagination

Hope that helps

**Comment by franckyg** [comment]
Yes, thank you !
