### ISSUE TITLE
friends/{username} returns all users, not only friends

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [DeviantArt/DeviantArt-API#97]
Hi,
there's seems to be a bug, as the API call returns a lot of users, who are actually not friends at all and have field friends:false.

**Comment by redcapital** [comment]
The "friend" field really corresponds to the "friend" checkbox in the watch settings. `/friends/{username}` returns people watched by 'username'

**Comment by Viachaslau-Zinkevich** [comment]
Is there any information about this issue?

**Comment by muteor** [comment]
The behaviour is correct `friends:false` is valid when the user has configured to watch a user without being a "friend"

For example:

![image](https://cloud.githubusercontent.com/assets/305164/15052096/bce14d76-12f3-11e6-8ee2-7b59c78b5e7a.png)

**Comment by Viachaslau-Zinkevich** [comment]
So, am I right to understand, that  friends/{username} means ALL people YOU watch? And /user/watchers/{username} means ALL users who watch YOU?

**Comment by muteor** [comment]
Yes

**Comment by Viachaslau-Zinkevich** [comment]
Thanks!
