### ISSUE TITLE
Deviation UUID changes on title rename?

### ISSUE THREAD

**Issue by cdennl** [DeviantArt/DeviantArt-API#98]
Hi,
is this correct behaviour that the uuid ID of a deviation changes, if the user edits the deviation, e.g. changing the title? How can I track that a deviation changed?

**Comment by redcapital** [comment]
UUID is assigned permanently and doesn't change. 

One way to track deviation changes is to cache response from /deviation/{deviationid} call and compare attributes later, though it really depends on your use case.

**Comment by cdennl** [comment]
Alright thank you. Then the user didn't only change a title but deleted and reuploaded the deviation. thank you very much. That is fine.
